### ISSUE TITLE
buffercache not populating, even after pg_buffercache installed

### ISSUE THREAD

**Issue by lobojohnson** [darold/pgcluu#100]
Hi,

it does not collect information about the buffercache.

i have tried both the parameter --enable-buffercache and -B, but no luck.

**Comment by darold** [comment]
Hi,

Commit 77c2611 fixes this issue introduced with commit b61bf44 to secure search_path before executing SQL queries. Now the call to pg_buffercache is always prefixed by the public schema. Please let me know if you use an other schema in this case I will add an option to change the schema where the pg_buffercache table can be found.

Best regards.

**Comment by lobojohnson** [comment]
Hi,

No, using public schema.

Get Outlook for Android<https://aka.ms/ghei36>
