### ISSUE TITLE
Purge when rotating files or when maxsize reached

### ISSUE THREAD

**Issue by Krysztophe** [darold/pgcluu#103]
As discussed this morning:

Is it possible to have a daily/weekly/monthly  purge, or according to the size of the data dir ?

When pgcluu_collectd rotates files, it does not remove anything.  `--maxsize` stops  the pgcluu_collectd.

As of 2.9, Debian now launches pgcluu_collects by default, so the collectd directory can fill the disk. Adding a purge with cron is possible but would be a hack.

Or did I miss something?

**Comment by darold** [comment]
Commit 061e685 adds option `--retention NDAYS` to pgcluu_collectd to set the number of rolling days to keep in data directory in incremental mode. Default is to store indefinitely.

Perhaps Debian should launch pgcluu_collectd with option `--retention 7` to only keep data for the rolling week.

**Comment by darold** [comment]
Note that when using incremental mode / data files rotation for a long period it is a good practice to compress data at rotation using `-z | --compress`. If gzip is installed this can save lot of space.

**Comment by darold** [comment]
@ChristophBerg I will publish a new release this night there is already enough changes to justify a new release.

**Comment by darold** [comment]
The amount of data stored by pgcluu_collected has been reduced, the out of space problem might not raised after a very long time or never following the `--compress` and `--retention` option. I'm closing this issue.

**Comment by Krysztophe** [comment]
Merci Gilles :+1:
