### ISSUE TITLE
Separate read and written buffers in "background writer clean stats"

### ISSUE THREAD

**Issue by gleu** [darold/pgcluu#106]
Right now, we have "checkpoint", "clean", "backend", and "allocated" buffers. The first 3 ones are written buffers and the latter one is read buffers. There's usually way much more read buffers than written ones, so the written buffers graphs are all flat out and unreadable because of this. And what we mostly need is definitely not "allocated" buffers. Moreover, we don't have an easy way to make "allocated" buffers disappear.

So, I think pgcluu should separate written and read buffers in two graphs. It would help a lot.

**Comment by darold** [comment]
Good remark Guillaume, commit dccc8b4 moved "allocated" buffers into a dedicated report.
