### ISSUE TITLE
psql:<stdin>:1: ERROR:  column con.consrc does not exist

### ISSUE THREAD

**Issue by seadba** [darold/pgcluu#107]
hello, awesome tool - testing latest 3v against 12.3 - not sure if this is a version issue or not

-bash-4.2$ pgcluu_collectd  -E 660 /data/pg12/sitewatch/pgcluu_log/

*** pgcluu_collectd v3.0 (pid:55931) started at Wed Sep 18 12:53:41 2019
Type Ctrl+c to quit.

psql:<stdin>:1: ERROR:  column con.consrc does not exist
LINE 1: ...ent(cn.nspname) || '.' || quote_ident(c.relname), con.consrc...
                                                             ^
HINT:  Perhaps you meant to reference the column "con.conkey" or the column "con.conbin".
psql:<stdin>:1: ERROR:  column con.consrc does not exist
LINE 1: ...ent(cn.nspname) || '.' || quote_ident(c.relname), con.consrc...

**Comment by devrimgunduz** [comment]
I just got the same error while testing the RPMs. Apparently this does not work against PostgreSQL 12.

**Comment by darold** [comment]
Release v3.1 published. Thanks.
