### ISSUE TITLE
Makefile.PL: install_all.sh's DESTDIR handling is broken

### ISSUE THREAD

**Issue by df7cb** [darold/pgcluu#108]
Hi,
pgcluu finally got accepted into Debian main, and I used the opportunity to update the package to 3.1.
I was pleased to find a full-fledged installation routine in install_all.sh which looked like it could obsolete all of my debian/pgcluu.install file. Unfortunately, the way the file handles DESTDIR is completely broken. The idea behind DESTDIR (which will be $(CURDIR)/debian/tmp for the package build) is to prepend an extra path component to all paths used for installing files, but leave the files themselves unmodified (i.e. DESTDIR must not be embedded into any file).
The existing logic fails in several ways:
* DESTDIR is prepended to /bin, but PREFIX is missing (which should be /usr)
* DESTDIR is missing for all other paths (CONFDIR, RSCDIR, ...)
* DESTDIR is written into pgcluu.service and pgcluu_collectd.service

I tried patching the issues, but it amounts to completely rewriting the file, so this should better be handled upstream.
Cheers,
Christoph

**Comment by darold** [comment]
I hope this time I have understood the way DESTDIR vs PREFIX works. Commit 994b9a7 fixes this issue at least it does what I have understood :-). Thanks for your patience Christoph!

Cheers.

**Comment by df7cb** [comment]
Hi,
I finally got around to package a new version. The DESTDIR/PREFIX handling is now correct (except for one minor issue, see #111).
Thanks!
