### ISSUE TITLE
3.1 and PostgreSQL 9.5 issue

### ISSUE THREAD

**Issue by devrimgunduz** [darold/pgcluu#110]
Hi,

I'm seeing this when I run pgcluu 3.1 against 9.5:

relation "pg_statistic_ext" does not exist at character 404
 STATEMENT:  COPY (SELECT date_trunc('seconds', now()), current_database(), cn.nspname AS schemaname, c.relname AS tablename, sn.nspname AS stat_schemaname, s.stxname AS stat_name, pg_get_userbyid(s.stxowner) AS stat_owner, (SELECT array_agg(a.attname ORDER BY a.attnum) AS array_agg FROM unnest(s.stxkeys) k(k) JOIN pg_attribute a ON a.attrelid = s.stxrelid AND a.attnum = k.k) AS attnames, s.stxkind AS kinds FROM pg_statistic_ext s JOIN pg_class c ON c.oid = s.stxrelid LEFT JOIN pg_namespace cn ON cn.oid = c.relnamespace LEFT JOIN pg_namespace sn ON sn.oid = s.stxnamespace WHERE NOT (EXISTS (SELECT 1 FROM unnest(s.stxkeys) k(k) JOIN pg_attribute a ON a.attrelid = s.stxrelid AND a.attnum = k.k WHERE NOT has_column_privilege(c.oid, a.attnum, 'select'::text))) AND (c.relrowsecurity = false OR NOT row_security_active(c.oid))) TO STDOUT CSV DELIMITER ';';

Can you please check?

Thanks!

**Comment by darold** [comment]
Hi Devrim,

That's true, thanks for the report. I forgot to remove this metric when PG < 10. Commit faa1212 fixes it.

Cheers,
