### ISSUE TITLE
mode cgi failed in debian stretch with cache

### ISSUE THREAD

**Issue by kikijolicoeur** [darold/pgcluu#114]
Hello Gilles (from Paris :-) )
I installed pgcluu from postgresql apt repository(3.1-1.pgdg90+1) . I want to use cgi-mode (to have reports from date to date). I updated /etc/pgcluu.conf to set STATS_REPORT_CACHING to 1 (initialy 0). I run manually  (as postgres user) : pgcluu --cache /var/lib/pgcluu/data. It works fine. I updated /lib/systemd/system/pgcluu.service and replace ExecStart=/usr/bin/pgcluu -o $REPORTDIR $STATDIR by ExecStart=/usr/bin/pgcluu --cache $STATDIR. systemctl daemon-reload. I use pgcluu.timer.
But when pgcluu runs (after 5 mn) with timer : pgcluu exits with the following errors:
Magic number checking on storable file failed at /usr/lib/x86_64-linux-gnu/perl/5.24/Storable.pm line 407, at /usr/bin/pgcluu line 11451.
Warning: unable to close filehandle GEN1 properly: Bad file descriptor at /usr/share/perl/5.24/Carp.pm line 167

For tests, I removed all .bin files from /var/lib/pgcluu/data : I ran pgcluu --cache /var/lib/pgcluu/data (as postgres user) and it works. I ran again and I have the same errors. pgluu -cache can only be run once.

Any idea ?
Thanks a lot for your work on pgcluu and pgbadger.

Christian

**Comment by darold** [comment]
Hi Christian,

I was able to reproduce the problem with an old data repository. The problem appears when pgcluu generate a cache file for an empty file:
```
-rw-r-----  1 postgres postgres        0 janv.  2 23:14 sys_cache.bin
-rw-r--r--  1 postgres postgres        0 oct.  18 23:08 sysinfo.txt
```
```
DEBUG: Loading system information from cache file /var/lib/pgcluu/data/2019/10/18/sys_cache.bin
Magic number checking on storable file failed at /usr/lib/x86_64-linux-gnu/perl/5.26/Storable.pm line 407, at pgcluu line 11455.
Warning: unable to close filehandle GEN1 properly: Bad file descriptor at /usr/share/perl/5.26/Carp.pm line 167.
```

There is two problems here, the sysinfo.txt file should not be empty I guess that it appears after a crash or a brutal interrupt. For the second, pgCluu should not build a cache file from an empty file or at least do not try to read it using Storable as it fail with error above. 

Commit 7a73198 fixes these two problems. Please download latest development code and give it a try.

**Comment by kikijolicoeur** [comment]
Hi Gilles.
Thanks a lot for your commit. pgcluu --cache is now ok when I run it more than once. But there is a side effect : As soon I run pgcluu --cache (manually ot by systemd), I lost the two menus "Cluster" and "Database" and the sysfinfo page content is : No system information available. If I delete the *.bin files from /var/lib/pgcluu/data/2020/01/03/, the menus and sysinfo come back.

Christian

**Comment by darold** [comment]
Please post the result of `ls -la /var/lib/pgcluu/data/2020/01/03/`

**Comment by kikijolicoeur** [comment]
Hi Gilles. 
rw-r----- 1 postgres www-data   496014 Jan  3 15:58 all_class_size.bin
-rw-r----- 1 postgres www-data       58 Jan  3 15:58 all_database_buffercache.bin
-rw-r----- 1 postgres www-data       54 Jan  3 15:58 all_database_isdirty.bin
-rw-r----- 1 postgres www-data      293 Jan  3 15:58 all_database_size.bin
-rw-r----- 1 postgres www-data       57 Jan  3 15:58 all_database_usagecount.bin
-rw-r----- 1 postgres www-data      252 Jan  3 15:58 all_db_role_setting.bin
-rw-r----- 1 postgres www-data       58 Jan  3 15:58 all_db_role_setting_diff.bin
-rw-r----- 1 postgres www-data     3601 Jan  3 15:58 all_nondefault_settings.bin
-rw-r----- 1 postgres www-data      636 Jan  3 15:58 all_pgbouncer_ini.bin
-rw-r----- 1 postgres www-data       56 Jan  3 15:58 all_pgbouncer_ini_diff.bin
-rw-r----- 1 postgres www-data       57 Jan  3 15:58 all_pgbouncer_req_stats.bin
-rw-r----- 1 postgres www-data       53 Jan  3 15:58 all_pgbouncer_stats.bin
-rw-r----- 1 postgres www-data     1732 Jan  3 15:58 all_pg_hba_conf.bin
-rw-r----- 1 postgres www-data       54 Jan  3 15:58 all_pg_hba_conf_diff.bin
-rw-r----- 1 postgres www-data       51 Jan  3 15:58 all_pg_ident_conf.bin
-rw-r----- 1 postgres www-data       56 Jan  3 15:58 all_pg_ident_conf_diff.bin
-rw-r----- 1 postgres www-data       58 Jan  3 15:58 all_postgresql_auto_conf.bin
-rw-r----- 1 postgres www-data       63 Jan  3 15:58 all_postgresql_auto_conf_diff.bin
-rw-r----- 1 postgres www-data     1417 Jan  3 15:58 all_postgresql_conf.bin
-rw-r----- 1 postgres www-data       58 Jan  3 15:58 all_postgresql_conf_diff.bin
-rw-r----- 1 postgres www-data       51 Jan  3 15:58 all_prepared_xact.bin
-rw-r----- 1 postgres www-data       51 Jan  3 15:58 all_recovery_conf.bin
-rw-r----- 1 postgres www-data       56 Jan  3 15:58 all_recovery_conf_diff.bin
-rw-r----- 1 postgres www-data       58 Jan  3 15:58 all_relation_buffercache.bin
-rw-r----- 1 postgres www-data    31946 Jan  3 15:58 all_settings.bin
-rw-r----- 1 postgres www-data       51 Jan  3 15:58 all_settings_diff.bin
-rw-r----- 1 postgres www-data      433 Jan  3 15:58 all_stat_archiver.bin
-rw-r----- 1 postgres www-data      583 Jan  3 15:58 all_stat_bgwriter.bin
-rw-r----- 1 postgres www-data      440 Jan  3 15:58 all_stat_connections.bin
-rw-r----- 1 postgres www-data    29851 Jan  3 15:58 all_stat_count_indexes.bin
-rw-r----- 1 postgres www-data     2311 Jan  3 15:58 all_stat_database.bin
-rw-r----- 1 postgres www-data      876 Jan  3 15:58 all_stat_database_conflicts.bin
-rw-r----- 1 postgres www-data       62 Jan  3 15:58 all_stat_extended_statistics.bin
-rw-r----- 1 postgres www-data       55 Jan  3 15:58 all_stat_hash_indexes.bin
-rw-r----- 1 postgres www-data       58 Jan  3 15:58 all_stat_invalid_indexes.bin
-rw-r----- 1 postgres www-data       57 Jan  3 15:58 all_statio_user_indexes.bin
-rw-r----- 1 postgres www-data       56 Jan  3 15:58 all_statio_user_tables.bin
-rw-r----- 1 postgres www-data     1130 Jan  3 15:58 all_stat_locks.bin
-rw-r----- 1 postgres www-data     1396 Jan  3 15:58 all_stat_missing_fkindexes.bin
-rw-r----- 1 postgres www-data      422 Jan  3 15:58 all_stat_redundant_indexes.bin
-rw-r----- 1 postgres www-data       54 Jan  3 15:58 all_stat_replication.bin
-rw-r----- 1 postgres www-data       53 Jan  3 15:58 all_stat_statements.bin
-rw-r----- 1 postgres www-data       51 Jan  3 15:58 all_stat_unlogged.bin
-rw-r----- 1 postgres www-data    10978 Jan  3 15:58 all_stat_unused_indexes.bin
-rw-r----- 1 postgres www-data       57 Jan  3 15:58 all_stat_user_functions.bin
-rw-r----- 1 postgres www-data       55 Jan  3 15:58 all_stat_user_indexes.bin
-rw-r----- 1 postgres www-data       54 Jan  3 15:58 all_stat_user_tables.bin
-rw-r----- 1 postgres www-data      521 Jan  3 15:58 all_tablespace_size.bin
-rw-r----- 1 postgres www-data      219 Jan  3 15:58 all_xlog_stat.bin
-rw-r--r-- 1 postgres www-data    13552 Jan  3 23:59 commit_memory.csv
-rw-r--r-- 1 postgres www-data    90275 Jan  3 23:59 end-pg_statio_user_indexes.csv
-rw-r--r-- 1 postgres www-data     2187 Jan  3 23:59 end-pg_statio_user_sequences.csv
-rw-r--r-- 1 postgres www-data    68499 Jan  3 23:59 end-pg_statio_user_tables.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 23:59 end-pg_stat_user_functions.csv
-rw-r--r-- 1 postgres www-data    92553 Jan  3 23:59 end-pg_stat_user_indexes.csv
-rw-r--r-- 1 postgres www-data   105271 Jan  3 23:59 end-pg_stat_user_tables.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 23:59 end-pg_stat_xact_user_functions.csv
-rw-r--r-- 1 postgres www-data    55236 Jan  3 23:59 end-pg_stat_xact_user_tables.csv
-rw-r--r-- 1 postgres www-data   390104 Jan  3 23:59 fs_stat_use.csv
-rw-r----- 1 postgres www-data       97 Jan  3 15:58 global_databases.bin
-rw-r----- 1 postgres www-data     1968 Jan  3 15:58 global_infos.bin
-rw-r----- 1 postgres www-data       78 Jan  3 15:58 global_tbspnames.bin
-rw-r--r-- 1 postgres www-data     8994 Jan  3 23:59 pgbouncer.ini
-rw-r--r-- 1 postgres www-data   458587 Jan  3 23:59 pg_class_size.csv
-rw-r--r-- 1 postgres www-data   123420 Jan  3 23:59 pg_database_size.csv
-rw-r--r-- 1 postgres www-data      678 Jan  3 23:59 pg_db_role_setting.csv
-rw-r--r-- 1 postgres www-data     6518 Jan  3 23:59 pg_hba.conf
-rw-r--r-- 1 postgres www-data     1636 Jan  3 23:59 pg_ident.conf
-rw-r--r-- 1 postgres www-data    12057 Jan  3 23:59 pg_nondefault_settings.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 15:56 pg_prepared_xact.csv
-rw-r--r-- 1 postgres www-data    93198 Jan  3 23:59 pg_settings.csv
-rw-r--r-- 1 postgres www-data    29524 Jan  3 23:59 pg_stat_archiver.csv
-rw-r--r-- 1 postgres www-data    52272 Jan  3 23:59 pg_stat_bgwriter.csv
-rw-r--r-- 1 postgres www-data    33548 Jan  3 23:59 pg_stat_connections.csv
-rw-r--r-- 1 postgres www-data    93496 Jan  3 23:59 pg_stat_count_indexes.csv
-rw-r--r-- 1 postgres www-data   124872 Jan  3 23:59 pg_stat_database_conflicts.csv
-rw-r--r-- 1 postgres www-data   312180 Jan  3 23:59 pg_stat_database.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 23:59 pg_stat_ext.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 23:59 pg_stat_hash_indexes.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 23:59 pg_stat_invalid_indexes.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 15:56 pg_statio_user_indexes.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 15:56 pg_statio_user_sequences.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 15:56 pg_statio_user_tables.csv
-rw-r--r-- 1 postgres www-data   428403 Jan  3 23:59 pg_stat_locks.csv
-rw-r--r-- 1 postgres www-data     1720 Jan  3 23:59 pg_stat_missing_fkindexes.csv
-rw-r--r-- 1 postgres www-data     1246 Jan  3 23:59 pg_stat_redundant_indexes.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 15:56 pg_stat_replication.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 23:59 pg_stat_unlogged.csv
-rw-r--r-- 1 postgres www-data    13011 Jan  3 23:59 pg_stat_unused_indexes.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 15:56 pg_stat_user_functions.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 15:56 pg_stat_user_indexes.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 15:56 pg_stat_user_tables.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 15:56 pg_stat_xact_user_functions.csv
-rw-r--r-- 1 postgres www-data        0 Jan  3 15:56 pg_stat_xact_user_tables.csv
-rw-r--r-- 1 postgres www-data    79860 Jan  3 23:59 pg_tablespace_size.csv
-rw-r--r-- 1 postgres www-data    29524 Jan  3 23:59 pg_xlog_stat.csv
-rw-r--r-- 1 postgres www-data       88 Jan  3 23:59 postgresql.auto.conf
-rw-r--r-- 1 postgres www-data    22927 Jan  3 23:59 postgresql.conf
-rw-r----- 1 postgres www-data      245 Jan  3 15:58 sar_block_stat.bin
-rw-r----- 1 postgres www-data      196 Jan  3 15:58 sar_commit_memory_stat.bin
-rw-r----- 1 postgres www-data      161 Jan  3 15:58 sar_context_stat.bin
-rw-r----- 1 postgres www-data      276 Jan  3 15:58 sar_cpu_stat.bin
-rw-r----- 1 postgres www-data      216 Jan  3 15:58 sar_dirty_stat.bin
-rw-r----- 1 postgres www-data      197 Jan  3 15:58 sar_load_stat.bin
-rw-r----- 1 postgres www-data      347 Jan  3 15:58 sar_memory_stat.bin
-rw-r----- 1 postgres www-data      353 Jan  3 15:58 sar_neterror_stat.bin
-rw-r----- 1 postgres www-data      291 Jan  3 15:58 sar_networks_stat.bin
-rw-r----- 1 postgres www-data      437 Jan  3 15:58 sar_pageswap_stat.bin
-rw-r----- 1 postgres www-data      182 Jan  3 15:58 sar_process_stat.bin
-rw-r----- 1 postgres www-data     1503 Jan  3 15:58 sar_rw_devices_stat.bin
-rw-r----- 1 postgres www-data     1004 Jan  3 15:58 sar_space_devices_stat.bin
-rw-r----- 1 postgres www-data     1216 Jan  3 15:58 sar_srvtime_stat.bin
-rw-r--r-- 1 postgres www-data 39749468 Jan  3 23:59 sar_stats.dat
-rw-r----- 1 postgres www-data      167 Jan  3 15:58 sar_swap_stat.bin
-rw-r----- 1 postgres www-data      891 Jan  3 15:58 sar_util_devices_stat.bin
-rw-r----- 1 postgres www-data    11582 Jan  3 15:58 sys_cache.bin
-rw-r--r-- 1 postgres www-data    15074 Jan  3 23:59 sysinfo.txt

Christian

**Comment by darold** [comment]
Not reproducible, closing.
