### ISSUE TITLE
pgcluu can't open compressed files ( IO::Handle: bad open mode: -| )

### ISSUE THREAD

**Issue by daamien** [darold/pgcluu#116]
Hi Gilles,

I hope you are well in these very strange times....

We encountered an issue with a collect directory that compressed like this

```
$ pgcluu_collectd [...] --rotate-daily  --compress collect_dir 
```

pgcluu fails to generate the report like this

```
$ pgcluu collect_dir -o report_dir                                                                                                                                 
IO::Handle: bad open mode: -| at /usr/bin/pgcluu line 10975.
```

If we remove the `--compress` option or simply unzip the collect files manually, the error disappears

```
$ gunzip -r collect_dir
$ pgcluu collect_dir -o report_dir  
$ echo $?                                                                                                                                                      
0                                  
```

My perl knowledge is very limited but I looked at the code and it seems that the syntax below is incorrect:

```perl
$fh = IO::File->new("$ZCAT_PROG $file", '-|');
```

The `-|` mode is used only in 3 parameters form of the new function.  In 2 parameters forms, the dash must be replaced by the command itself like this:

```perl 
$fh = IO::File->new("$ZCAT_PROG $file |");
```

Same thing with `open()`.

Again I'm not sure that I understand all aspects of this problem but with this change pgcluu is able to open zipped files.

Let me know if you want me to push a PR for that...

Have a nice day and take care..

**Comment by darold** [comment]
Hi Damien,

Yes, everything well on my side. Thanks for the report, commit 82b256c solves this issue.

I hope you and your family are staying healthy.
