### ISSUE TITLE
The Pgcluu report doesn't display the configuration files

### ISSUE THREAD

**Issue by cyberioio** [darold/pgcluu#117]
Hello,
when i generate a pgcluu (v3.1) report (html), it doesn't display the configuration files (postgresql.conf, pg_hba.conf, ...)
while the data are well collected and well written in the source of the html page (cluster-pgconf.html, cluster-pghba.html, ...).
I don't understand why ...
Can you help me please ?
Thanks in advance.
[cluster-pgconf.zip](https://github.com/darold/pgcluu/files/4891261/cluster-pgconf.zip)

Lionel

**Comment by cyberioio** [comment]
Additional info : when i remove the tag "cluster-pgconf-slide", it works ...
Strange ...

**Comment by darold** [comment]
Thanks for the report, commit 62e9ab1 fixes this issue.
