### ISSUE TITLE
Integration metrics with pg_stat_statements

### ISSUE THREAD

**Issue by cheucheu** [darold/pgcluu#121]
Hi

It's not a issue but a evolution idea.

Have you planned  in your backlog l'integration of specific dashboards around Activity SQL with the extension pg_stat_statements ?

Best Regards

**Comment by darold** [comment]
What reports are you thinking about? Currently pgcluu reports pg_stat_statement informations when the extension is found in a database. It reports: `Calls | Avg time | Total time | Rows | Temp blocks written | Query`.

**Comment by darold** [comment]
Update: more precisely this is when the extension is found in the connection  database, you could have to use `-d dbname` to pgcluu_collectd to specify this database if the extension have not been created in the default connection database.

**Comment by cheucheu** [comment]
Hi 

OK i don't have precised  the option.  Thanks, i test it and i come back with you.
Thanks a lot of !

**Comment by cheucheu** [comment]
Hi

It's OK.  I have ran the collect as below.

=> pgcluu_collectd -D -i 60 -h localhost -d testbig /pgqdata/backup/pgserver01/www  -f /tmp/1.pid

The extension pg_stats_statements is active and the table is populated.
testbig=# select count(*) from pg_stat_statements;
 count
-------
   160
(1 row)


Best regards
