### ISSUE TITLE
Support of postgresql:// and "host=... port=..." syntax?

### ISSUE THREAD

**Issue by Krysztophe** [darold/pgcluu#122]
Hi,

To connect to a remote DB, it seems that pgcluu_collectd does accept  the -h/-d/-U/-p  or  PGPORT/PGDATABASE/PGUSER/PGHOST, or services, not the 'postgresql://' or 'host= port= dbname=...' syntax.

Such a string after ''--dbname'' is accepted but seems ignored.

Did I miss something?

That could be useful in a script that provides such connection strings.

**Comment by darold** [comment]
Yes this is not supported and will probably not be supported as the work to support it is not negligible and as you said there is already all the options to set the connection to remote host. Closing because I don't see when I could find time to implement it.

**Comment by Krysztophe** [comment]
I may try to add it, at least for simple cases, but I  fear conflicts with other options, and I have the same problem of available time...
