### ISSUE TITLE
How to customize REPORTDIR variable to be used by systemctl services?

### ISSUE THREAD

**Issue by jphuart** [darold/pgcluu#131]
I've created an environment variable with

`export REPORTDIR=/my/favorite/path` 

but the reports continues to be generated in the default dir `/var/lib/pgcluu/report`.

I'd like to be able to define such variable in the /etc/pgcluu.conf file. 
Thanks
Jean Pierre Huart

**Comment by darold** [comment]
Commit 134e86a adds this feature.
