### ISSUE TITLE
pgcluu.conf default values

### ISSUE THREAD

**Issue by jphuart** [darold/pgcluu#132]
This morning a server stopped because no more memory was left. 

Pgcluu_collectd.service was running for more than 2 years without any maintenance. 

The guy that implemented it left the team and forgot to tell about it to the one that replaces him (guess who).

Of course, partition configuration was not the best one. 

By the way, may I suggest that default values for `STATS_COLLECTD_RETENTION` and `STATS_REPORT_RETENTION` should be set to `30` instead of `0`?

**Comment by darold** [comment]
Commit a3fe91b make this change. Thanks for the report.
