### ISSUE TITLE
Time for a 3.2 release?

### ISSUE THREAD

**Issue by Krysztophe** [darold/pgcluu#133]
Hi,

Release 3.1 is already 2 years old. As the packages maintainers rely on the Github releases, the CentOS and Debian packages are totally out of date.
Do you plan to release a 3.2 soon?

Merci!

**Comment by darold** [comment]
Damned, I don't realized that it was two years old, thanks for the reminder, I will publish a new release asap.

**Comment by MichaelDBA** [comment]
ha, funny

**Comment by darold** [comment]
I think the Covid thing change my perception of time :-)

**Comment by darold** [comment]
New released v3.2 published, see https://github.com/darold/pgcluu/releases/tag/v3.2

**Comment by Krysztophe** [comment]
MErci !
