### ISSUE TITLE
pg_stat_statements.total_time & v13

### ISSUE THREAD

**Issue by Krysztophe** [darold/pgcluu#135]
Version: current master branch

`pgcluu_collectd -v` gives me this:
```
psql:<stdin>:54: ERROR:  column "total_time" does not exist
LINE 1: ...[ \n]+', ' ', 'g'), E';', '#SMCLN#', 'g'), calls, total_time...
```
That seems to be related to pg_stat_statements.
In PG13, `total_time` was replaced by `total_plan_time` and `total_execution_time`.

**Comment by ng-pe** [comment]
Hello,
I just pushed a PR to fix this for pg13 and above.
Regards
