### ISSUE TITLE
pgbouncer queries freeze when not in daemon mode due to `psql -f -`

### ISSUE THREAD

**Issue by Krysztophe** [darold/pgcluu#137]
Version: github master

In daemon mode, all is fine, I get the pgbouncer CSV files.

When NOT in daemon mode (eg when I have another problem...), I get only an empty file.

More precisely, a query such as this one never finishes and stops the metrics collection:
```bash
$ ps faux|grep psql
postgres 3878981  0.0  0.0   2608   608 pts/2    S+   17:51   0:00  |   |               \_ sh -c psql -XAtq -F';' -f -  -p6432 pgbouncer -c "SHOW STATS" | sed 's/^/2022-01-26 17:51:41;/' >> /tmp/pgcluutest//pgbouncer_req_stats.csv
postgres 3878982  0.5  0.0  21500  9056 pts/2    S+   17:51   0:00  |   |                   \_ /usr/lib/postgresql/14/bin/psql -XAtq -F; -f - -p6432 pgbouncer -c SHOW STATS
```
and I never get any file:
```bash
$ sudo ls -l /tmp/pgcluutest//pgbouncer*csv
-rw-r--r-- 1 postgres postgres 0 janv. 26 17:51 /tmp/pgcluutest//pgbouncer_req_stats.csv
```

I can reproduce on the command line : I must quit myself or it hangs:
```bash
$ sudo -iu postgres psql -XAtq -F';' -f- -p6432 pgbouncer -c "SHOW STATS"|sed 's/^/2022-01-26 17:51:41;/' 
\q
2022-01-26 17:51:41;pagode14_local;5672;39460;2434847;1054070;2013760343;2006157258;12556;0;0;0;0;0;0;0
2022-01-26 17:51:41;pgbouncer;160;160;0;0;0;0;0;0;0;0;0;0;0;0
```
Without `-f -` it works:
```bash
$ sudo -iu postgres psql -XAtq -F';'  -p6432 pgbouncer -c "SHOW STATS"|sed 's/^/2022-01-26 17:51:41;/' 
2022-01-26 17:51:41;pagode14_local;5672;39460;2434847;1054070;2013760343;2006157258;12556;0;0;0;0;0;0;0
2022-01-26 17:51:41;pgbouncer;161;161;0;0;0;0;0;0;0;0;0;0;0;0
```

As a test, I've removed the `-f -` on: https://github.com/darold/pgcluu/blob/50d32cae1d860e6a6f0c4f63f5cfe0a1336e8962/pgcluu_collectd#L763
and everything seems fine.
But I suppose that some things may be messed up, as there are still `open` and `print` commands in the code.

**Comment by darold** [comment]
Right, the `-f -` option must be removed from the psql command for pgbouncer statistic collect. Fixed with commit 1ce772c.
