### ISSUE TITLE
Report generation fails sometimes/often due to missing  end-pg_stat_user_tables.csv or end-pg_stat_user_indexes.csv

### ISSUE THREAD

**Issue by Krysztophe** [darold/pgcluu#148]
About halt the time, the report generation fails with this error:
<code>
FATAL: can't read file  pgcluu_output_dir/./end-pg_stat_user_indexes.csv: No such file or directory
</code>

I can create the file with `touch` and I get then:
<code>
FATAL: can't read file pgcluu_output_dir/./end-pg_stat_user_tables.csv: No such file or directory
</code>

Another `touch` and I get my report, of course with 'Tables statistics' and 'Indexes statistics' missing.

I haven't really understood why and how it fails yet, but it's painful. Any idea?

**Comment by darold** [comment]
This has been fixed.
