### ISSUE TITLE
Failed to show cgi report,why?

### ISSUE THREAD

**Issue by geostar123** [darold/pgcluu#157]
I succeeded in generating static html report,but got failed for cgi report.
  I used pgcluu_collectd command as below to collect statistics data,and made a cron task to generate bin file.But httpd server reported errors while opening http://addr1.addr2.addr3.addr4:80/cgi-bin/pgcluu.cgi

command:  
 pgcluu_collectd  -D -i 60  --rotate-daily /var/lib/pgcluu/data -h addr1.addr2.addr3.addr4 -U geoadmin -d postgres -p 5432
 crontab -e
  */5 * * * *  /usr/local/bin/pgcluu   --cache /var/lib/pgcluu/data

 httpd webserver error:
  [Tue Aug 30 12:17:14.855819 2022] [cgi:error] [pid 13678] [client addr1.addr2.addr3.addr4:                                                                                                         57325] AH01215: FATAL: can't write to /var/lib/pgcluu/data/2022/08/30/pidstat_cp                                                                                                             u_stat.bin, No such file or directory
   .....
   Any help will be appreciated!

**Comment by darold** [comment]
Supposing that you run pgcluu_collectd and pcluu as postgres system user you must execute the following commands:
```
        /bin/chown -R postgres:www-data /var/lib/pgcluu/data/
        /bin/chmod -R u=rwX,g=rsX,o= /var/lib/pgcluu/data/
```

**Comment by geostar123** [comment]
thanks to @darold.
I  use geoadmin as user,not postgres.I have already open all access (rwx) for folder /var/lib/pgcluu/data.You maybe take a look at web error: can't write to /var/lib/pgcluu/data/2022/08/30/pidstat_cp u_stat.bin, No such file or directory.I found no pidstat_cpu_statbin file existing in folder  /var/lib/pgcluu/data/2022/08/30,why?

**Comment by geostar123** [comment]
@darold.could you provide a cgi example for me like    web http://pgcluu.darold.net/example/ showing html ?

**Comment by darold** [comment]
The HTML outtput is exactly the same as the reports generated by pgcluu, this is just that they are generated dynamically from the *.bin files instead of static HTML.

Actually the CGI should not write to disk so I had a deeper look at the error message above and this the wrong message, it should be a read error. Commit 06fd626 fix this problem.

The problem is that the binary files are not generated by the cron command. You should try to run manually as geoadmin user the command `/usr/local/bin/pgcluu --cache /var/lib/pgcluu/data`, it will show you the error.

**Comment by geostar123** [comment]
thanks again.You are right.I mannualy run command "pgcluu --cache /var/lib/pgcluu/data",then it did generated some .bin files,but no pidstat*.bin ,pls see the following:

![图片](https://user-images.githubusercontent.com/30171754/187375025-5c21d790-c76a-4ab3-bff4-8b036803fc84.png)

**Comment by geostar123** [comment]
In order to generate pidstat*.bin files,I tried running command " /usr/local/bin/pgcluu -i /var/log/sa/sa30 --from-sa-file  --cache /var/lib/pgcluu/data".Unfortunately,web page (http://addr1.addr2.addr3.addr4:80/cgi-bin/pgcluu.cgi could not show any graph.

**Comment by geostar123** [comment]
![图片](https://user-images.githubusercontent.com/30171754/187376813-4ad1e009-2d28-4970-91d4-0150bfd7eaf6.png)

Now there are pidstat*.bin files in /var/lib/pgcluu/data subfolder,but these bin files' length is less than 100 bytes.
The cgi page show nothing as below:

![图片](https://user-images.githubusercontent.com/30171754/187377551-1acb38b1-cfcc-446c-8f74-0277deb68241.png)

**Comment by darold** [comment]
Thanks for the additional explanation, commit 76ada65 now verify that the pidstat* binary file exists before.

The CGI doesn't generate reports because the binary files are empty.

**Comment by darold** [comment]
You can not use a dedicated sar binary file to generate the reports, pgcluu_collectd  has already called sar to generate the system statistics.

The pgcluu command should be `/usr/local/bin/pgcluu --cache /var/lib/pgcluu/data`

**Comment by geostar123** [comment]
Running command "/usr/local/bin/pgcluu --cache /var/lib/pgcluu/data" will not generate pidstat*.bin files on my pc.

I tried pgcluu with two method(rpm installation and source code compilation),but got the same result.-:)
According to your explanation,why I generate empty bin files?How to solve this problem?

**Comment by geostar123** [comment]
By the way,my pgcluu version is  3.3.0(both rpm and source code).

**Comment by darold** [comment]
As I explain to you above, the CGI mode can only be run on a data directory generated by pgcluu_collectd. When you use `pgcluu  -i /var/log/sa/sa30 --from-sa-file --cache /var/lib/pgcluu/data` you are erasing all stats built by pgcluu_collectd.

**Comment by geostar123** [comment]
Well,thanks for your patience.As I described above:If running pgcluu command without -i and --from-sa-file parameters,there will be no pidstat*.bin files generated.If there is no pidstat*.bin file in folder,apache httpd server will report errors.So What can I do to fix the issue?

**Comment by darold** [comment]
Use latest development code from github, I have fixed the error in the commit mentioned above or apply these changes to your current installation.

**Comment by geostar123** [comment]
ok.let me try.please keep your attention to this issue.thanks again.

**Comment by geostar123** [comment]
ok.let me try.please keep your attention to this issue.I will not close this issue until it get fixed.
thanks again.

**Comment by geostar123** [comment]
@darold.Just now i tried by apply changes 06fd626(https://github.com/darold/pgcluu/commit/06fd626bf1f1c3eb8ade100e81758952cc35c0ed) and 76ada65(https://github.com/darold/pgcluu/commit/76ada65daf31a079054fc8a59458f9360f627bfb) to pgcluu.cgi,there are pidstat*.bin files generated in /var/lib/pgcluu/subfolder.Unfortunately,these bin files are all empty,why?I assure you that pgbench are always running on remote server addr1.addr2.addr3.addr4.

![图片](https://user-images.githubusercontent.com/30171754/187389992-c32a2a20-dc4b-46c3-9702-c18f61d27d0a.png)

**Comment by geostar123** [comment]
crontab  for user geoadmin:
*/5 * * * * /usr/local/bin/pgcluu    --cache /var/lib/pgcluu/data

**Comment by geostar123** [comment]
@darold,Just now i tried by applying changes https://github.com/darold/pgcluu/commit/06fd626bf1f1c3eb8ade100e81758952cc35c0ed(https://github.com/darold/pgcluu/commit/06fd626bf1f1c3eb8ade100e81758952cc35c0ed) and https://github.com/darold/pgcluu/commit/76ada65daf31a079054fc8a59458f9360f627bfb(https://github.com/darold/pgcluu/commit/76ada65daf31a079054fc8a59458f9360f627bfb) to pgcluu.cgi,there is no pidstat*.bin file generated in /var/lib/pgcluu/data subfolder,why?I assure you that pgbench are always running on remote server addr1.addr2.addr3.addr4.


![图片](https://user-images.githubusercontent.com/30171754/187393857-2a101bae-acf8-4d13-8670-172a3d6af189.png)

web server report:
![图片](https://user-images.githubusercontent.com/30171754/187393979-5e418641-fbb5-4271-bacc-484e45e6d11e.png)

**Comment by darold** [comment]
The error message still reports "can't write to ..." and in new code after the patches:
```
$ grep "can't write to" cgi-bin/pgcluu.cgi | wc -l
0
```
I guess that you have not modified the right CGI file, you should patch the one that is executed by your HTTP server.

**Comment by geostar123** [comment]
![图片](https://user-images.githubusercontent.com/30171754/187409344-f14080ef-6b62-4220-b47a-421707dbd3f4.png)

**Comment by geostar123** [comment]
I commented  all   'can't write to....' lines,now web server reported the following:
![图片](https://user-images.githubusercontent.com/30171754/187410697-2954bd5d-bed8-48aa-9043-db6a7be0af50.png)

**Comment by geostar123** [comment]
The key issue still remains unfixed.There is no pidstat*.bin file generate in /var/lib/pgcluu/data subfolder.With your help I hope this can be fixed.

**Comment by darold** [comment]
Ok, please do the following:
```
wget https://github.com/darold/pgcluu/archive/refs/heads/master.zip
unzip master.zip
cd pgcluu-master/
perl Makefile.PL
make
sudo make install
cp -f cgi-bin/pgcluu.cgi /var/www/cgi-bin/
```
that should override your installion of pgcluu with latest development code.

Then verify with `grep "can't write to" /var/www/cgi-bin/pgcluu.cgi | wc -l`

Also perhaps you could also try to restart your HTTP server, especially if you use mod_perl.

**Comment by geostar123** [comment]
ok.let me try

**Comment by geostar123** [comment]
@darlod.I did these steps you metioned above on a new pc,but got the same.As i metioned before,the key issue remains unfixed:pidstat*.bin file will not generate in /var/lib/pgcluu/data subfolder.

My pgcluu_collectd command line:
  pgcluu_collectd  -D -i 60  --rotate-daily /var/lib/pgcluu/data -h addr1.addr2.addr3.addr3 -U geoadmin -d postgres -p 5432
  pgcluu --cache /var/lib/pgcluu/data
My crontab task:
  
  */5 * * * * /usr/local/bin/pgcluu   --cache /var/lib/pgcluu/data

the latest pgcluu.cgi:
![图片](https://user-images.githubusercontent.com/30171754/187573790-32f092d0-4c95-472d-85fd-7922aa499ec1.png)

/var/lib/pgcluu/data/2022/08/31 folder:
![图片](https://user-images.githubusercontent.com/30171754/187574422-65a77552-d982-42ed-903a-88089d6703ec.png)


httpd webserver report:
![图片](https://user-images.githubusercontent.com/30171754/187573852-c218c1cc-7ab6-497b-8612-1a9bef22f059.png)

**Comment by geostar123** [comment]
Looking forward to you reply.

**Comment by darold** [comment]
Thanks for the report, commit 79d2daf might solve this issue. You can just proceed as previously when installing latest development code.

**Comment by geostar123** [comment]
thanks to @darlod.let me try.

**Comment by geostar123** [comment]
thanks to @darlod.let me try.
I applied the newest patch 79d2daf to pgcluu.cgi,web server did not report errors as metioned above(..Uninitialized $sar_file). As i metioned   more times,the key issue remains unfixed:pidstat*.bin file will not generate in /var/lib/pgcluu/data subfolder,and all generated bin files are almost empty(see picture below) while I used the above pgcluu_collectd command line.

![图片](https://user-images.githubusercontent.com/30171754/187615786-103d4fd2-f651-4e57-839b-de3755daeadc.png)

pls pay attention to this issue.

**Comment by geostar123** [comment]
web cgi page:
![图片](https://user-images.githubusercontent.com/30171754/187616198-8bed075d-3881-4939-b76f-678fc411c168.png)

**Comment by geostar123** [comment]
**_apart from pgcluu.cgi bugs,pgcluu_collectd will not generate pidstat*.bin files and other generated bin files are all empty._**

**Comment by darold** [comment]
First you must copied the resources file into your html directory as follow:
```
sudo mkdir  /var/www/html/pgcluu/
sudo cp -rf cgi-bin/rsc/ /var/www/html/pgcluu/
sudo chown -R www-data: /var/www/html/pgcluu/
```
the interface will have a better look.

Second, I have installed pgcluu with the command above and create the data directory as follow:
```
/bin/chown -R postgres:www-data /var/lib/pgcluu/data/
/bin/chmod -R u=rwX,g=rsX,o= /var/lib/pgcluu/data/
```
then run pgcluu_collectd few minutes:
```
/usr/local/bin/pgcluu_collectd -i 60 -I /var/lib/pgcluu/data/ -f /tmp/pgcluu_collectd.pid --disable-sar
```
then build the cache:
```
/usr/local/bin/pgcluu --cache /var/lib/pgcluu/data --disable-sar
```
and looking at the CGI screenshot everything is alright.

![Capture d’écran de 2022-08-31 09-31-41](https://user-images.githubusercontent.com/538862/187621352-9cf5d9a3-4e79-4fdf-bb38-3b86dc4dbae1.png)

So my opinion is that your run of pgcluu_collectd is failing but as it is run in daemon mode you do not see the error. Do the following. Stop the daemon:
```
pgcluu_collectd -k
```
Run pgcluu_collectd in interactiv mode (without the -D option) and have a look at the errors
```
pgcluu_collectd -i 10 --rotate-daily /var/lib/pgcluu/data -h addr1.addr2.addr3.addr3 -U geoadmin -d postgres -p 5432
```

**Comment by geostar123** [comment]
First,run pgcluu_collectd command without -D option,there is no error occured.

![图片](https://user-images.githubusercontent.com/30171754/187629837-11d55d6a-ca2d-418f-ab21-2340420bd809.png)

**Comment by geostar123** [comment]
second:create a folder in /var/www/html and copy cgi-bin/rsc into it.
![图片](https://user-images.githubusercontent.com/30171754/187630513-acfd5b83-8923-472f-b98f-984a95da40aa.png)

![图片](https://user-images.githubusercontent.com/30171754/187630597-25691e82-f79f-45f3-9f6c-299cf31a0027.png)

![图片](https://user-images.githubusercontent.com/30171754/187630688-fe9c675e-ad3e-4c4b-b747-a30e6cf76b87.png)

**Comment by geostar123** [comment]
according to your steps,all i can do  have been done,but got the same:no pidstat*.bin files generated,others are empty,and cgi page shown as below:
![图片](https://user-images.githubusercontent.com/30171754/187637276-8949ef7f-0f15-4937-8b48-64d4fa130286.png)

**Comment by darold** [comment]
Well I can not put much more attention to this issue, I'm not able to reproduce the problem.

Maybe you should not use the CGI mode and build static html pages by running periodically pgcluu.

**Comment by geostar123** [comment]
by the way,must i use postgres user?except geoadmin user
It's my advice that you should install pgcluu on non-development computer or virtual machine and verify this issue.

**Comment by geostar123** [comment]
ok.thank you.
