### ISSUE TITLE
Old pidstat doesn't have the -U switch

### ISSUE THREAD

**Issue by gleu** [darold/pgcluu#162]
I'm talking really old, such as 9.0.4, but I had one customer with such a beast. So pgcluu should probably check pidstat release and use it only if it has the -U switch.

**Comment by darold** [comment]
Commit 2dfa744 adds the --disable-pidstat option to pgcluu_collectd to handle such case.

**Comment by gleu** [comment]
Crap, you're right. I should have known. Sorry for the noise.

**Comment by darold** [comment]
@gleu, this is a new option added last night so you could not know :-)
