### ISSUE TITLE
Sysstat 12.7.6 In ETCP , retrans/s renamed  to retrseg/s

### ISSUE THREAD

**Issue by Krysztophe** [darold/pgcluu#173]
See https://github.com/sysstat/sysstat/commit/e33b6500f7d6a54ce0182a5790fd494313201a86

This version is not currently released yet.

**Comment by darold** [comment]
Hi @Krysztophe thanks for the report, actually the ETCP sar output is not collected by pgcluu so we might not be affected by this change.

**Comment by Krysztophe** [comment]
Objection: it is!

https://github.com/darold/pgcluu/pull/147/files

**Comment by Krysztophe** [comment]
> RIght I may have made a typo when looking at retrans and ETCP. Reopened.
> 
> Do you want to fix that?

I'll try to do it soon.

**Comment by darold** [comment]
It is fixed with commit 91ec29b9 actually only the graph legends needed to be fixed. I have removed the sar label inside them.
