### ISSUE TITLE
Error column "shared_blks_hit" not exists

### ISSUE THREAD

**Issue by juliomartini** [darold/pgcluu#33]
Hello,

Greate app. Congratulations!
I'm running the collector and get the following result: 

  ./pgcluu_collectd -i 60 /tmp/test -U postgres 

Pgcluu_collectd *** v2.1 (pid: 1478) started at Tue Oct 21 15:04:44 2014 
Type Ctrl + c to quit. 

ERROR: sar execution failure: 
psql: <stdin>: 27: ERROR: "shared_blks_hit" column does not exist 
LINE 1: ..., E ';', 'SMCLN # #', 'g'), calls, TOTAL_TIME, rows, shared_blk ... 

Version: psql (PostgreSQL) 9.3.4 

Any idea?

**Comment by darold** [comment]
I think I can close this issue, let us know if you still have the same issue with latest release.
