### ISSUE TITLE
Does pgcluu have any knowledge of timezones?

### ISSUE THREAD

**Issue by dcramble** [darold/pgcluu#42]
Is there a way I can set pgcluu to adjust the localtime output for my timezone? It seems the stats being dumped are using UTC time. I would like to configure my system to adjust the time in relation to my timezone if possible.

**Comment by darold** [comment]
Yes David, see -z option of pgcluu:

  -z, --timezone +/-XX     Set the number of hour(s) from GMT of the timezone.
                           Use this to adjust date/time from the sar output,
                           pgcluu use GMT time to draw charts.

This is probably what you are looking for.

**Comment by dcramble** [comment]
Thank you. I'm GMT -8. The charts all have the correct time scale on them without me adding any timezone options. However, the date/time on the first page of the report output (index.html), under "Cluster" and under "System" have a date/time which appears to be GMT. I tried:

```bash
$ pgcluu --timezone -8
```

and also:

```bash
$ pgcluu -z -8
```
The date/time still appear to be GMT. Is the timezone flag meant to adjust the date/time under the Cluster and System overview sections, or just those of the charts?

If I add the timzone correction (28800 seconds) to $OVERALL_STATS{'start_date'} and $OVERALL_STATS{'end_date'} in pgcluu, then the date/time appear correct on the Cluster and System overview. Is it possible $tz correction should be added to those dates as well and was just missed? If so, I can submit a pull request.

**Comment by darold** [comment]
It will adjust time for charts only. A pull request is welcome to fix that.

**Comment by dcramble** [comment]
I could use a little guidance here.

It would seem that my system is outputting the correct time for the charts, without out any timezone correction needed. If I use the -z option with my patch, I end up with correct time for the Cluster and System stats, but incorrect time for all of my charts. It would seem that sar on my system (Centos 6) is dumping "local corrected" time, but perl localtime() is using UTC. Thus my conclusion is there must be a capability to adjust the timezone correction for sar and localtime() independently to cover all possible system configurations.

My proposed solution would be to have a timezone option for each as follows:

```perl
"z|timezone=s"          => \$TIMEZONE,
"Z|stats-timezone=s" => \$STATS_TIMEZONE,
```

However, I don't know if you would consider this the best approach. My desire is to create a pull request that you would find useful. If you have thoughts on this approach, I would be very interested.

**Comment by darold** [comment]
It make sens to me to have two command line options to be able to adjust the timezone from the two different sources: sar and PostgreSQL. I'm agree with your proposed solution.

**Comment by dcramble** [comment]
Created Pull Request #43

**Comment by darold** [comment]
Thanks David, it has been applied.
