### ISSUE TITLE
unable execute collectd due to FATAL:psql error

### ISSUE THREAD

**Issue by sksajid7** [darold/pgcluu#44]
Hi Darold,

Need you help, I'm unable execute collectd due to FATAL:psql error
pgcluu_collectd  -i 10 /tmp/stat_db1/ -d tpch

*** pgcluu_collectd v2.3 (pid:5527) started at Thu Apr  2 14:11:23 2015
Type Ctrl+c to quit.

FATAL: psql error.

Checked all the queries from script which could lead to above error:

postgres=# SELECT version();
                                                    version
---------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.3.4 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-52), 64-bit
(1 row)

postgres=# SELECT extname||'-'||extversion FROM pg_extension;
  ?column?
-------------
 plpgsql-1.0
(1 row)

postgres=# SELECT datname FROM pg_database WHERE NOT datistemplate AND datallowconn;
         datname
-------------------------
 postgres
 rodb
 cidb
 tedb
 ratdb
 gerandb
 trandb
 acdb
(8 rows)

postgres=# SELECT nspname FROM pg_namespace WHERE nspname !~ '^pg_' AND nspname <> 'information_schema' ORDER BY 1;
 nspname
---------
 public
(1 row)

postgres=# SELECT proname FROM pg_proc WHERE proname = 'pg_buffercache_pages';
 proname
---------
(0 rows)

postgres=# SELECT n.nspname||'.'||p.proname FROM pg_proc p, pg_namespace n WHERE p.proname='pg_stat_statements' AND p.pronamespace=n.oid;
 ?column?
----------
(0 rows)

postgres=# SELECT n.nspname||'.'||p.proname FROM pg_proc p, pg_namespace n WHERE p.pronamespace=n.oid AND n.nspname NOT IN ('pg_catalog', 'information_schema');
 ?column?
----------
(0 rows)

postgres=# SELECT count(tgname) FROM pg_trigger WHERE NOT tgisinternal;
 count
-------
     0
(1 row)

postgres=# SELECT setting FROM pg_settings WHERE name IN ('config_file','hba_file','ident_file','data_directory') ORDER BY name;
             setting
----------------------------------
 /opt/ood/db/data/postgresql.conf
 /opt/ood/db/data
 /opt/ood/db/data/pg_hba.conf
 /opt/ood/db/data/pg_ident.conf
(4 rows)

**Comment by darold** [comment]
Hi,

Please download latest code from github and post here the error message returned, there has been a patch to make this error message more verbose. We will be able to see what error psql is facing.

This error is related to the execution of the psql command, perhaps it is not in the path or the user running pgcluu_collected doesn't have the right to connect to PG, or some other psql connection reason.

Regards,

**Comment by sksajid7** [comment]
Noticed that psql path is not picked up by pgcluu_collectd script and I downloaded latest code(master.zip) to be sure, then manually updated the path. 
- my $PSQL_PROG   = '/opt/oodee/pgsql/bin/psql';

Couldn't complete run as root or postgres user, due to prompt of password:

# pgcluu_collectd  -i 10 /tmp/stat_db1/ -U postgres

*** pgcluu_collectd v2.3 (pid:11695) started at Thu Apr  2 15:14:43 2015
Type Ctrl+c to quit.

Password for user postgres:
Password for user postgres:
Password for user postgres:
Password for user postgres:

Postgres user:

$ pgcluu_collectd  -i 10 /home/postgres/ -U postgres

*** pgcluu_collectd v2.3 (pid:11598) started at Thu Apr  2 15:13:26 2015
Type Ctrl+c to quit.

Password for user postgres:
Password for user postgres:
Password for user postgres:
Password for user postgres:

*** pgcluu_collectd v2.3 (pid:11238) started at Thu Apr  2 15:09:33 2015
Type Ctrl+c to quit.

Password:
FATAL: psql error. psql.bin: FATAL:  password authentication failed for user "root"

**Comment by sksajid7** [comment]
Thanks Darold for this exceptional tool.

updated DBUSER and DBPASS with postgres, then the script works just fine.
