### ISSUE TITLE
pgcluu's sysinfo.txt is mostly Linux-only

### ISSUE THREAD

**Issue by jasperla** [darold/pgcluu#46]
I imported a port of pgcluu into [OpenBSD ports](http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/databases/pgcluu/) earlier today. It generally works fine (the PostgreSQL part that is), however there are two issues:

- there's no `sar` binary for `sysstat` is effectively a wrapper for `cat /proc/*`
- the other sysinfo related parts of `pgcluu` rely heavily on `/proc` too, or other Linuxisms such as swap or filesystem information.

Has it been considered to use a more widely supported library to grab the information? Such as libstatgrab or the like? That way `sysinfo.txt`'s os-related content can be replaced with library calls and therefore making it more portable and as a bonus, preventing the need to shell-out.

**Comment by darold** [comment]
Hi,

Sorry for responding so late, I was traveling. One of the main feature
of pgcluu is that it doesn't not require anything to be installed, other
than Perl, to be able to collect PostgreSQL metrics. The use of sar is
optional and doesn't prevent us to use pgcluu if it is not installed. If
you keep in mind this feature I will be pleased to apply your pull
requests for OpenBSD support. You can use the Unix::Statgrab Perl
Module, we will included it later into the pgcluu_collectd script.

Best regards,

**Comment by jasperla** [comment]
Alright, then let's close this issue and I'll open PRs or more separate issues when I need to discuss specifics.
