### ISSUE TITLE
Always getting stats for all my databases

### ISSUE THREAD

**Issue by Assem** [darold/pgcluu#48]
Hello,

I'm doing some tests with your tool, and for now, I have a small problem: I try to get only stats for one database in my server, but I always get stats for all DB. I tried:

pgcluu -o /tmp/report_mathon_143/ /tmp/stat_mathon_dev/ --db-only mathon_143

and

pgcluu_collectd -D -i 10 /tmp/stat_mathon_dev/ --dbname mathon_143

Thkx

**Comment by darold** [comment]
Hi,

You are confusing pgcluu_collectd option --dbname with --included-db. The first one is use to set the database to connect using psql and to be able to collect statistics. The second is use to limit the statistics collect to a comma separated list of database name.

So you must run the following commands:

     pgcluu_collectd -D -i 10 /tmp/stat_mathon_dev/ --dbname mathon_143 --included-db=mathon_143

    pgcluu -o /tmp/report_mathon_143/ /tmp/stat_mathon_dev/ --db-only mathon_143

Having to different options for the same things (--db-only and --included-db) is historical, sorry for that.

I have updated the pgcluu_collectd usage and documentation about --included-db which has wrongly the description of an --excluded-db instead. This last option does not exists.

Please download last development code and let us know.

Best regards,

**Comment by Assem** [comment]
Hi,

I just downloaded the actual version of master: I did the install like indicated in the readme file (I have already the old version of pgcluu but I suppose this won't causes problems).

Now when I run:

> pgcluu_collectd -D -i 10 /tmp/stat_mathon_dev/ --included-db=mathon_dev

I get:

> Global symbol "$db_limit" requires explicit package name at /usr/local/bin/pgcluu_collectd line 1813.
> Execution of /usr/local/bin/pgcluu_collectd aborted due to compilation errors.

**Comment by darold** [comment]
Sorry, please download again, last commit b886d4a remove some debug garbage.

**Comment by Assem** [comment]
Now when I ran:
> pgcluu -o /tmp/report_gs/ /tmp/stat_gs/ --db-only gs_prod_2015_06_19

I get a lot of warnings:
> Use of uninitialized value in concatenation (.) or string at /usr/local/bin/pgcluu line 3316.
> Use of uninitialized value in concatenation (.) or string at /usr/local/bin/pgcluu line 3317.

But the report is generated for one database only so it's good for me ;)

Thkx

**Comment by darold** [comment]
Could you send me (gilles@darold.net) your data files, uninitialized value warning should not happen ?

**Comment by darold** [comment]
Thanks a lot for your help, last commit ede771d fix this last issue as well as a wrong overall statistics in the main Home report.

**Comment by Assem** [comment]
Welcome :)

By the way, I have a small question: your application doesn't collect detailed informations about executed queries? Like time by query?

**Comment by darold** [comment]
I should report such information but you need to install pg_stat_statements extension into the pgcluu_collectd connection database.  in your case:

    psql mathon_143 -c "CREATE EXTENSION pg_stat_statements"

Or if it  already exists pgcluu_collectd must connect to that database.

**Comment by Assem** [comment]
Hi again,

I have done like you said:
psql mathon_143 -c "CREATE EXTENSION pg_stat_statements"

Where can I find the list of queries and the details info for each one?

Also, why some stats are showed for some DB and not for others?

Thks

**Comment by darold** [comment]
I think pull request #49 might fix this issue.  For each database that have queries in pg_stat_statement you will have a submenu called " Statements statistics" and the top queries for this database. Please update pgcluu code from github it should works now.
