### ISSUE TITLE
Empty parts in reports

### ISSUE THREAD

**Issue by izenk** [darold/pgcluu#50]
Hello.
pgcluu_collectd --version
Version: 2.3
pgcluu --version
Version: 2.3

Collection statistic command is:
pgcluu_collectd -d database -h host -p5432 --rotate-daily -z -i 10 -S -T -C 1 -U user --password password --pgversion 9.4 /statistics/

Analyze command is:
pgcluu -d database -n 0 -o /reports/statistics/ -S -v /statistics/

In general everything works fine, but have some issues:
1) Some parts of report are empty, for example "background writer clean stats" or "background writer count stats" or "checkpoints counter stats"
![index](https://cloud.githubusercontent.com/assets/6417697/8935757/0d430a1e-3557-11e5-9aad-c3db155ec646.png)
![index1](https://cloud.githubusercontent.com/assets/6417697/8935842/7b42801c-3557-11e5-8ec7-ad56951fc459.png)
![index2](https://cloud.githubusercontent.com/assets/6417697/8935862/94b18278-3557-11e5-89de-b0e823a76c95.png)

I also use pgbadger version 7.0 and it shows me info about background writer and checkpoints, that's why I know, that statistic information about it is present and available.

2) I enable incremental reports. That is structure created by pgcluu:
##### statistics (pgcluu_collectd) (output dir is /statistics)
ls -1 /statistics/2015/07/28/
pg_class_size.csv
pg_database_size.csv
pg_db_role_setting.csv
pg_settings.csv
pg_stat_archiver.csv
pg_stat_bgwriter.csv
pg_stat_connections.csv
pg_stat_database_conflicts.csv
pg_stat_database.csv
pg_statio_user_indexes.csv
pg_statio_user_sequences.csv
pg_statio_user_tables.csv
pg_stat_locks.csv
pg_stat_missing_fkindexes.csv
pg_stat_redundant_indexes.csv
pg_stat_replication.csv
pg_stat_unused_indexes.csv
pg_stat_user_functions.csv
pg_stat_user_indexes.csv
pg_stat_user_tables.csv
pg_stat_xact_user_functions.csv
pg_stat_xact_user_tables.csv
sysinfo.txt

##### reports (pgcluu) (output dir is /reports/statistics)
ls -1 /reports/statistics/
2015/
bootstrap.min.css
bootstrap.min.js
font-awesome.min.css
jquery.min.js
pgcluu.css
pgcluu.js
sorttable.js

###### reports (pgcluu) (output dir is /reports/statistics) but for one day
ls -1 /reports/statistics/2015/07/28/
activebilling-index-size.html
activebilling-table-size.html
cluster.html
database-activebilling.html
database-all.html
index.html

But, it seems some index-file skipped in /reports/statistics directory. Web server is pointed to /reports/statistics/, where as I understand some skipped index-file generated by pgcluu must be. This file will show some calendar or list of all available reports. But now I have to enter full path manually like: http://my-server/statistics/2015/07/28
Sorry, if I'm wrong about this issue item.

**Comment by darold** [comment]
Hi,

The principle of pgcluu_collectd is to run in background and collect statistics each minute or following the given interval. Here on you command line you use -C 1 which instruct pgcluu_collected to collect statistics one time and exit. So this is normal that some graph are empty, especially those with counter statistics. They need at least 2 values, the point in the graph will be the delta between them. So your comman should look like this:

    pgcluu_collectd -d database -h host -p5432 --rotate-daily -z -i 10 -S -T-U user --password password /statistics/

The version is not required too, pgcluu_collectd might be able to autodetect it.

"But now I have to enter full path manually like: http://my-server/statistics/2015/07/28", yes this is normal, incremental reports are a work in progress and need a dynamic CGI interface to be able to generate indexes on the fly. You have to generate report day per day for the moment.

I recommend you to download and use latest release 2.4, there's lot of bug fixes and for incremental report wait for next major release 3.0.

Best regards,

**Comment by izenk** [comment]
Thank you. Will try 2.4
