### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by sammcj** [darold/pgcluu#52]
Any plans to release packages for Debian / RHEL?
This would remove the need to install make etc... and make upgrades easier.

**Comment by darold** [comment]
Hi,

RPM package are already available at http://yum.postgresql.org/9.5/redhat/rhel-6-x86_64/repoview/letter_p.group.html thanks to the excellent work of Devrim.

Here it is for RHL6 but you can find the RPM corresponding to your RHL at http://yum.postgresql.org/packages.php then choose your distro and then the letter P to see all available package.

For Debian, this is an other thing. If you want to have an up to date version, the only way is to download sources from https://github.com/darold/pgcluu/releases

Regards,
