### ISSUE TITLE
Additional fct- entries in "Databases" drop-down menu

### ISSUE THREAD

**Issue by spritchard** [darold/pgcluu#53]
When I generate a report, the "Databases" menu in the resulting report has one entry for each of my databases: e.g. db1, db2, db3; but then it also has entries for fct-db1, fct-db2, fct-db3. There is no information for these fct- entries.

I think this is arising because the report contains files database-db1.html and also database-fct-db1.html, which contains the function stats. The code that generates the menu seems to be taking database-*.html.

**Comment by darold** [comment]
Thanks for the report, latest commits might fix that issue.

**Comment by spritchard** [comment]
Many thanks - that seems to have fixed it.

Now the sub-menu for the bottom database doesn't disappear off the bottom of the browser window!

Steve
