### ISSUE TITLE
sar report is broken

### ISSUE THREAD

**Issue by eulerto** [darold/pgcluu#55]
I tried the 'sar report only' but apparently it is broken:

$ sar -p -A 5 10 > /tmp/my_sar_file.txt 
$ ./pgcluu -o /tmp/report_sar/ -i /tmp/my_sar_file.txt 
FATAL: Can't open directory : No such file or directory

It seems that it broke after 'daily rotation' feature.

**Comment by darold** [comment]
Latest commit 0e5a959 might fix that issue. Thanks for the report.
