### ISSUE TITLE
Re: dyanamic report genaration

### ISSUE THREAD

**Issue by supriyakhosare** [darold/pgcluu#56]
Hi, 
Can we generate dynamic report using pgcluu.....?
So that we get current statistics from my server as soon as it is generated.

**Comment by darold** [comment]
Hi,

This is a work in progress, but to simplify, for the moment you can't. Actually there a cgi-bin directory in the source tree with a pgcluu.cgi script that will be used to provide the dynamic and "real time" functionality. It is near to be terminated (still need week/month/year view) and the most important it need to be documented. I need some time to work on it and it is a real problem to find spare time. I which to terminate this work in the next two months.

Best regards,

**Comment by supriyakhosare** [comment]
OK....
We are waiting for this new pgcluu. 
Thank You.
