### ISSUE TITLE
pgcluu "Invalid offset" with replicated instance and sar disabled

### ISSUE THREAD

**Issue by TonyIrisSU** [darold/pgcluu#60]
Bonjour,

Il semblerait que la génération du html via pgcluu pose problème soir sur les instances primaires répliquées :

[root@u3recu138 ~]# /var/lib/pgsql/pgcluu/pgcluu -v -o /var/lib/pgsql/pgcluu/html/pgsr021-5432/ /var/lib/pgsql/pgcluu/data/pgsr021-5432/ --disable-sar
(...)
DEBUG: reading statistics in file /var/lib/pgsql/pgcluu/data/pgsr021-5432/2015/09/22/pg_stat_replication.csv
Invalid offset: 0 at /var/lib/pgsql/pgcluu/pgcluu line 8478, <GEN15> line 1.

A noter : la collecte des données SAR a été désactivée.

Cordialement,
Tony LEGEAY

**Comment by darold** [comment]
Bonjour,

Normalement le commit 9ca3100 du mois dernir corrige de problème. Merci d'utiliser le code en développement et de vérifier si le problème persiste.

Cordialement,
