### ISSUE TITLE
pgcluu_collectd doesn't support daylight savings

### ISSUE THREAD

**Issue by brownbh3** [darold/pgcluu#61]
we are running pgcluu_collectd every 15 mintues with the following command pgcluu/pgcluu_collectd --compress --rotate-daily --daemonize --interval=900 --pgbouncer-args='-p 9999 -U admin -d pgbouncer' /mnt/backup/pgsql/stats/pgcluu

There is duplicated data for the hour for daylight savings.. went back one hour and created duplicate rows.

**Comment by darold** [comment]
Commit 0d51c36 prevent storing statistics twice when hour change during daylight saving by waiting until current time is upper than last running time.

Best regards
