### ISSUE TITLE
root password is not valid

### ISSUE THREAD

**Issue by gabx** [darold/pgcluu#66]
poisonivy@poppy ➤➤ ~ % sudo /usr/bin/pgcluu_collectd -i 240 /storage/psqlStat
[sudo] password for poisonivy: 

*** pgcluu_collectd v2.4 (pid:18549) started at Fri Jan  1 23:35:14 2016
Type Ctrl+c to quit.

Password: 
FATAL: psql error. psql: FATAL:  password authentication failed for user "root"

password is indeed correct. Why am I asked a second time for the root password?
Using fresh build from git, and cant remember such issue before.

**Comment by gabx** [comment]
i guess nothing to do with your package. Adding -D is OK, but nothing is collected and no /tmp/pid

**Comment by darold** [comment]
This is PostgreSQL that is asking you the password of the root user. Anyway if you don't have created a root user in PostgreSQL you won't be able to authenticate.

The recommended way to execute pgcluu_collectd is to use the postgres system user or to use -U to change the user.

```
sudo su - postgres
 /usr/bin/pgcluu_collectd -i 240 /storage/psqlStat
```

Note that adding -D won't help in this case, it will just deamonize pgcluu_collectd.

**Comment by gabx** [comment]
On Sat, Jan 2, 2016 at 12:30 AM, Darold <notifications@github.com> wrote:

> This is PostgreSQL that is asking you the password of the root user.
> Anyway if you don't have created a root user in PostgreSQL you won't be
> able to authenticate.
>

I have one.

> The recommended way to execute pgcluu_collectd is to use the postgres
> system user or to use -U to change the user.
>
> sudo su - postgres
>  /usr/bin/pgcluu_collectd -i 240 /storage/psqlStat
>
> postgres@poppy ➤➤ ~ % /usr/bin/pgcluu_collectd -i 240 /storage/psqlStat

*** pgcluu_collectd v2.4 (pid:18975) started at Sat Jan  2 00:39:07 2016
Type Ctrl+c to quit.

Password:
Password:

Password is asked twice. Then pgcluu_collectd is running:
$ ls /tmp
pgcluu_collectd.pid

I was just trying to play a little bit outside from starting it with
systemd service file.

Duno why I got lost.



>  Note that adding -D won't help in this case, it will just deamonize
> pgcluu_collectd.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/darold/pgcluu/issues/66#issuecomment-168350372>.
>



-- 

google.com/+arnaudgabourygabx
<https://plus.google.com/_/notifications/emlink?emr=05814804238976922326&emid=CKiv-v6PvboCFcfoQgod6msAAA&path=%2F116159236040461325607%2Fop%2Fu&dt=1383086841306&ub=50>

**Comment by gabx** [comment]
On Sat, Jan 2, 2016 at 12:45 AM, arnaud gaboury <arnaud.gaboury@gmail.com>
wrote:

>
>
> On Sat, Jan 2, 2016 at 12:30 AM, Darold <notifications@github.com> wrote:
>
>> This is PostgreSQL that is asking you the password of the root user.
>> Anyway if you don't have created a root user in PostgreSQL you won't be
>> able to authenticate.
>>
>
> I have one.
>
>> The recommended way to execute pgcluu_collectd is to use the postgres
>> system user or to use -U to change the user.
>>
>> sudo su - postgres
>>  /usr/bin/pgcluu_collectd -i 240 /storage/psqlStat
>>
>> postgres@poppy ➤➤ ~ % /usr/bin/pgcluu_collectd -i 240 /storage/psqlStat
>
> *** pgcluu_collectd v2.4 (pid:18975) started at Sat Jan  2 00:39:07 2016
> Type Ctrl+c to quit.
>
> Password:
> Password:
>
> Password is asked twice. Then pgcluu_collectd is running:
> $ ls /tmp
> pgcluu_collectd.pid
>
> I was just trying to play a little bit outside from starting it with
> systemd service file.
>
> Duno why I got lost.
>
>
Sorry for the noise. Everything is OK:

http://psql.thetradinghall.com/



>
>
>>  Note that adding -D won't help in this case, it will just deamonize
>> pgcluu_collectd.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/darold/pgcluu/issues/66#issuecomment-168350372>.
>>
>
>
>
> --
>
> google.com/+arnaudgabourygabx
> <https://plus.google.com/_/notifications/emlink?emr=05814804238976922326&emid=CKiv-v6PvboCFcfoQgod6msAAA&path=%2F116159236040461325607%2Fop%2Fu&dt=1383086841306&ub=50>
>
>


-- 

google.com/+arnaudgabourygabx
<https://plus.google.com/_/notifications/emlink?emr=05814804238976922326&emid=CKiv-v6PvboCFcfoQgod6msAAA&path=%2F116159236040461325607%2Fop%2Fu&dt=1383086841306&ub=50>
