### ISSUE TITLE
stop plcguu_collectd after n seconds

### ISSUE THREAD

**Issue by gabx** [darold/pgcluu#67]
```
postgres@poppy ➤➤ ~ % /usr/bin/pgcluu_collectd --end-after=300 /storage/psqlStat/

*** pgcluu_collectd v2.4 (pid:24227) started at Sat Jan  2 18:48:26 2016
Type Ctrl+c to quit.

Password:
```
******
Entered postgres password.
*******
```
poisonivy@poppy ➤➤ systemd/system % date
Sat Jan  2 18:54:27 CET 2016
poisonivy@poppy ➤➤ systemd/system % myps pgcluu
47:postgres 24227 24010  0 18:48 pts/1    00:00:00 pgcluu_collectd
```
*********
pgcluu_collectd is still running, Is it not supposed to stop after 300 sec ? 
*****
```
postgres@poppy ➤➤ ~ % ls -al /storage/psqlStat                                   
total 0
drwxrwxr-x 1 postgres postgres   0 Jan  2 18:48 ./
drwxrwxr-x 1 root     wheel    194 Jan  2 11:42 ../
```
************

Why is the directory empty? NOTE: my postgresql DB is not writing anything and do not see activity, but the service is running. Is it the reason?

**Comment by darold** [comment]
Please ugrade to latest development code, commit 1b72e4f fix an issue introduced with yesterday fix about daylight saving.

Sorry for the inconvenience.

**Comment by gabx** [comment]
Fresh build (git clone ...) does not change anything.

**Comment by gabx** [comment]
Things are a little better, but not perfect. The following command will populate my stat directory:
```
/usr/bin/pgcluu_collectd --end-after=300 --password='XXX' /storage/psqlStat/
*** pgcluu_collectd v2.4 (pid:24850) started at Sat Jan  2 20:21:29 2016
Type Ctrl+c to quit.

```
Unfortunately, the process is still running after 300 seconds.
No idea why, but entering postgres pwd at prompt seems to break pgcluu_collected

**Comment by darold** [comment]
Ok, commit 0c63dd1 might fix the last regression brings with that silly daylight saving patch.

Thanks for the report.

**Comment by gabx** [comment]
I can confirm ```--end-counter``` and ``-end-after``` options are now working.
TY for the modification
