### ISSUE TITLE
pgcluu_collectd crashes

### ISSUE THREAD

**Issue by microtodd** [darold/pgcluu#69]
During any run of pgcluu_collectd, on a fresh run crashes about a minute in, on a run with an existing stats dir crashes immediately.  Error message is:

bash-4.1$ /var/lib/pgsql/pgcluu-master/pgcluu_collectd -S -r -i 60 /var/lib/pgsql/pgcluu_stats -U postgres -d postgres

*** pgcluu_collectd v2.4 (pid:5735) started at Tue Apr  5 15:54:27 2016
Type Ctrl+c to quit.

Can't locate object method "new" via package "IO::File" (perhaps you forgot to load "IO::File"?) at /var/lib/pgsql/pgcluu-master/pgcluu_collectd line 2563.
bash-4.1$

Adding "use IO::File;" to the top of pgcluu_collectd seems to fix the problem.

Replicated on Red Hat Enterprise Linux 6.7 and Centos 6.7.

**Comment by darold** [comment]
Thanks for the report, I will drop a note in documentation. I don't know what what they are doing with the perl packaging, IO::FIle is in Perl code for years now.  What is your version of Perl ?

On a 6.7 vm here are the perl Package I have, I don't know in which rpm is the IO::File module:

```
perl-DBI-1.609-4.el6.x86_64
perl-libs-5.10.1-141.el6_7.1.x86_64
perl-Module-Pluggable-3.90-141.el6_7.1.x86_64
perl-5.10.1-141.el6_7.1.x86_64
perl-ExtUtils-ParseXS-2.2003.0-141.el6_7.1.x86_64
perl-Test-Harness-3.17-141.el6_7.1.x86_64
perl-Time-HiRes-1.9721-141.el6_7.1.x86_64
perl-DBD-Pg-2.15.1-4.el6_3.x86_64
perl-Pod-Escapes-1.04-141.el6_7.1.x86_64
perl-version-0.77-141.el6_7.1.x86_64
perl-Pod-Simple-3.13-141.el6_7.1.x86_64
perl-devel-5.10.1-141.el6_7.1.x86_64
perl-ExtUtils-MakeMaker-6.55-141.el6_7.1.x86_64
```

Best regards,

**Comment by microtodd** [comment]
[root@f00881714978 pgcluu-master]# perl -V
Summary of my perl5 (revision 5 version 10 subversion 1) configuration:
   
  Platform:
    osname=linux, osvers=2.6.32-220.el6.x86_64, archname=x86_64-linux-thread-multi
    uname='linux c6b8.bsys.dev.centos.org 2.6.32-220.el6.x86_64 #1 smp tue dec 6 19:48:22 gmt 2011 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Doptimize=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DDEBUGGING=-g -Dversion=5.10.1 -Dmyhostname=localhost -Dperladmin=root@localhost -Dcc=gcc -Dcf_by=Red Hat, Inc. -Dprefix=/usr -Dvendorprefix=/usr -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl5 -Dsitearch=/usr/local/lib64/perl5 -Dprivlib=/usr/share/perl5 -Darchlib=/usr/lib64/perl5 -Dvendorlib=/usr/share/perl5/vendor_perl -Dvendorarch=/usr/lib64/perl5/vendor_perl -Dinc_version_list=5.10.0 -Darchname=x86_64-linux-thread-multi -Dlibpth=/usr/local/lib64 /lib64 /usr/lib64 -Duseshrplib -Dusethreads -Duseithreads -Duselargefiles -Dd_dosuid -Dd_semctl_semun -Di_db -Ui_ndbm -Di_gdbm -Di_shadow -Di_syslog -Dman3ext=3pm -Duseperlio -Dinstallusrbinperl=n -Ubincompat5005 -Uversiononly -Dpager=/usr/bin/less -isr -Dd_gethostent_r_proto -Ud_endhostent_r_proto -Ud_sethostent_r_proto -Ud_endprotoent_r_proto -Ud_setprotoent_r_proto -Ud_endservent_r_proto -Ud_setservent_r_proto -Dscriptdir=/usr/bin -Dusesitecustomize'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.4.7 20120313 (Red Hat 4.4.7-16)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -fstack-protector'
    libpth=/usr/local/lib64 /lib64 /usr/lib64
    libs=-lresolv -lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc
    perllibs=-lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.12'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic'


Characteristics of this binary (from libperl): 
  Compile-time options: MULTIPLICITY PERL_DONT_CREATE_GVSV
                        PERL_IMPLICIT_CONTEXT PERL_MALLOC_WRAP USE_64_BIT_ALL
                        USE_64_BIT_INT USE_ITHREADS USE_LARGE_FILES
                        USE_PERLIO USE_REENTRANT_API USE_SITECUSTOMIZE
  Built under linux
  Compiled at Nov 10 2015 12:05:27
  @INC:
    /usr/local/lib64/perl5
    /usr/local/share/perl5
    /usr/lib64/perl5/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib64/perl5
    /usr/share/perl5
    .
[root@f00881714978 pgcluu-master]#

**Comment by microtodd** [comment]
IO::File is there, but it seemed like the "use" needed to be added to the perl script itself.

**Comment by darold** [comment]
Last commit fd845b6 will fix that.
