### ISSUE TITLE
Enchancement : Support EnterpriseDB

### ISSUE THREAD

**Issue by piotr-gbyliczek** [darold/pgcluu#70]
I have used pgcluu on commercial version of PostgreSQL from EnterpriseDB. 
It does not present itself as PostgreSQL in "select version();" output, hence pgcluu does not recognise version correctly. 

A fix is to add the alternative to the fetch_version subroutine : 

--- a/pgcluu_collectd
+++ b/pgcluu_collectd
@@ -1227,7 +1227,7 @@ sub fetch_version
        }
        chomp($pg_ver);
 
-       if ($pg_ver =~ /^PostgreSQL (\d+)\.(\d+)/) {
+       if ($pg_ver =~ /^(PostgreSQL|EnterpriseDB) (\d+)\.(\d+)/) {
                $DB_INFO{major} = $1;
                $DB_INFO{minor} = $2;
        }

Regards,
Piotr

**Comment by darold** [comment]
Thanks  Piotr, fixed in last commit 5b2d2ee .

Best regards,

**Comment by piotr-gbyliczek** [comment]
That's great, thanks.

To be honest, I found out later that one can set version on command line, which should be a workaround for such situations.

I was wondering how many versions of postgres exist that change the name in this fashion. I'm aware of few, 2nd Quadrant and PostgresXL for example, unsure if they changing it. 

Maybe worth looking at throwing a warning when version is not set, suggesting using --pgversion ? 

Anyway, this one is up to you, thanks again for fixing this one. 

Regards,
Piotr
