### ISSUE TITLE
pgCluu collector error with checkpoint_segments on PG 9.5

### ISSUE THREAD

**Issue by jmrprieto** [darold/pgcluu#73]
Collector issues the following query:

` COPY (SELECT date_trunc('seconds', now()), count(*) AS num_file, pg_xlogfile_name(pg_current_xlog_location()) AS current, sum(is_recycled::int) AS is_recycled, sum((NOT is_recycled)::int) AS written, CASE WHEN max_wal1 > max_wal2 THEN max_wal1 ELSE max_wal2 END AS max_wal FROM ( SELECT file > first_value(file) OVER w AS is_recycled ,1 + ( current_setting('checkpoint_segments')::float4 * ( 2 + current_setting('checkpoint_completion_target')::float4 )) AS max_wal1, 1 + current_setting('wal_keep_segments')::float4 + current_setting('**checkpoint_segments**')::float4 AS max_wal2 FROM pg_ls_dir('pg_xlog') as file WHERE file ~ '^[0-9A-F]{24}$' WINDOW w AS ( ORDER BY (pg_stat_file('pg_xlog/'||file)).modification DESC ) ) AS t GROUP BY 6 ) TO STDOUT CSV DELIMITER ';';
`

Which is invalid in PG 9.5 as parameter **checkpoint_segments** does not exist anymore.
It doesn't seem to impact the collection itself, report look fine, but if floods the PG log with error messages which may trigger alarms.

**Comment by darold** [comment]
Please use latest development code, this have been fixed in november last year, or wait few hours I will publish a new release today.

Best regards,

**Comment by jmrprieto** [comment]
It's fine, just a heads up. I can wait. Keep up the good work.
