### ISSUE TITLE
ERROR: can't find /tmp/pgcluu_collectd.pid, is pgcluu_collectd running?

### ISSUE THREAD

**Issue by Toredo85** [darold/pgcluu#75]
I installed pgcluu_collectd and do: 

> $ pgcluu_collectd -D -i 10 /tmp/stat_db1/ -h demo.rds.amazonaws.com -U postgresql -W HP5KUHhfNs1

And I get:

> $ LOG: Detach from terminal with pid: 20330

Then I try:

> $ pgcluu_collectd -k

and get:

> ERROR: can't find /tmp/pgcluu_collectd.pid, is pgcluu_collectd running?

why?

**Comment by darold** [comment]
Hi,

Maybe pgcluu_collectd  was interrupted because it encounter an error. In this case you have to run it in interactive mode by removing the  -D option and fix or report the error.

Note that instead of using -W you might want to use a .pgpass file to not expose your password in command line. pgcluu_collectd use psql to query your backend so it must support the .pgpass file.

Best regards,

**Comment by Toredo85** [comment]
Thank you! But now I get:

> sudo pgcluu_collectd -i 10 /tmp/stat_db1/ -h demo..rds.amazonaws.com -d postgres -U postgresql -W HP5zk6YxG9ENs1
> 
> *** pgcluu_collectd v2.5 (pid:32076) started at Mon Aug 22 19:09:32 2016
> Type Ctrl+c to quit.
> 
> psql:<stdin>:20: ERROR:  permission denied for database rdsadmin
> psql:<stdin>:32: ERROR:  permission denied for tablespace pg_global
> psql: FATAL:  pg_hba.conf rejects connection for host "52.25.97.170", user "post           gresql", database "rdsadmin", SSL on
> FATAL:  pg_hba.conf rejects connection for host "52.25.97.170", user "postgresql           ", database "rdsadmin", SSL off

What do I must to do?

I put .pgpass file to /root/ and to /var/lib/sudo/ , but it ask for the password anyway. Where should I put it in?

**Comment by darold** [comment]
I don't think you need to use sudo. Under your normal user account, just create a $HOME/.pgpass with 0600 privilege and execute pgcluu_collectd under this user account. Also you use `-U postgresql` I guess it should be `-U postgres` unless it has been changed. To check that your .pgpass is working, use first psql with same parameters:

    psql -h demo..rds.amazonaws.com -d postgres -U postgres

once it is working you can try with pgcluu_collectd.
