### ISSUE TITLE
Incomplete per-database-statistics

### ISSUE THREAD

**Issue by Markus-** [darold/pgcluu#77]
I started the collectd-Daemon yesterday by using the command:
`pgcluu_collectd -D -i 60 -r -z /performance/data`

Then I created the report by using the command:
`pgcluu -o /performance/reports /performance/data
`
When I go through the Interface, especially the per-db-stats are not complete.
While in your example there are several entries under tables (Index ratio...) in my report there is just "Size-and-Tuples". Same valid for indexes.

The file "pg_stat_user_tables.csv" is created by pgcluu_collectd (while pg_stat_all_tables.csv is not) - so the data should be there.

Did I miss anything during collecting the data / creating the report?
Regards
Markus

**Comment by darold** [comment]
Markus,

Please download latest code from github, last commit 5d46410 might solves this issue.

Let me know,

**Comment by Markus-** [comment]
darold,

just installed it and tried it for about 15 minutes. The missing statistics are there now.
I think it's working now.

Thanks for the fix.
Regards
Markus
