### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Pedramrn** [darold/pgcluu#78]
It would be nice to have a docker image of this project.

**Comment by darold** [comment]
If you are looking for a package, you can install it using yum or apt-get. See yum.postgresql.org and apt.postgresql.org . I don't know how a docker image can be useful, but I don't know docker.

**Comment by michelvosje** [comment]
It might be a useful for your project to look into it.

You can build and provide an official pgcluu Docker image on the [Docker Hub](https://hub.docker.com/) site. People who are interested in your project and just want to quickly launch their own demo pgcluu environment can find your project on the Docker hub. They'll then see a short project description and information about how the Docker image can be started using a simple command like:

 $ docker run -p 80:8000 --name pgcluu pgcluu:1.0

Which means:
* Docker downloads the Docker pgcluu image with version 1.0.
* Docker binds the local port 80 to the docker container port 8000.

Assuming that their Docker Machine runs on 192.168.99.100 they can now reach the pgcluu website using the URL: [https://192.168.99.100](https://192.168.99.100).

You as a develop could include in the Docker image:
* Installation of pgcluu including configurations.
* Running sample PostgreSQL database.
