### ISSUE TITLE
ERROR: can't find /tmp/pgcluu_collectd.pid, is pgcluu_collectd running?

### ISSUE THREAD

**Issue by manishhub9** [darold/pgcluu#80]
I a unable to monitor my postgres. I install and runn but its not collecting data fron postgres.

**Comment by darold** [comment]
What is the output of command: `pgcluu_collectd -i 10 /path/to/stat_data/`

**Comment by manishhub9** [comment]
first i try : pgcluu_collectd -D -i 60 /tmp/stat_db1/
no result collected
and :  pgcluu_collectd -D -i 60 /tmp/stat_db1/ -h ip_address -U postgres -d postgres

no result collected

**Comment by kkostenko** [comment]
Hitting the same issue, pgcluu seem to silently dye without any diagnostics:
lnx:7603> pgcluu_collectd -D -i 60 /tmp/stat_db1/ 
LOG: Detach from terminal with pid: 16554
lnx:7604> ps -aef | grep pgc
xxx      16562 31186  0 09:47 pts/1    00:00:00 grep pgc

**Comment by kkostenko** [comment]
that happen when pgcluu is unable to connect to DB. Why? All depends, in my case I figured it out, but having some diagnostics would help for sure.

**Comment by darold** [comment]
The error is dump to stderr but the detach mode does not show you the error into your terminal. To know what's going wrong you have to run pgcluu_collectd in interactive mode and remove the -D option:

     pgcluu_collectd -i 60 /tmp/stat_db1/

You will see the error output on your terminal.
