### ISSUE TITLE
Error: column "waiting" does not exist

### ISSUE THREAD

**Issue by ldrlj1** [darold/pgcluu#81]
The waiting column was removed from pg_stat_activity in Postgres 9.6.

In pgcluu_collectd the dump_pgstatactivity and dump_pgstatconnections functions pull the waiting column. I commented out those references and reran, then pgcluu choked when trying to build a report.  The error from pgcluu is "Use of unitialized value $db is hash element at line ...:

**Comment by darold** [comment]
Hi,

Yes that's right, please use latest development code this might have been fixed. Use git clone or download an archive:

    wget https://github.com/darold/pgcluu/archive/master.zip

Best regards,
