### ISSUE TITLE
pgCluu 2.5 does not collect stats under PostgreSQL 9.6

### ISSUE THREAD

**Issue by pgrepli** [darold/pgcluu#82]
Hello,

Tested "pgCluu" 2.5 with PostgreSQL 9.6, "pgcluu_collectd" did not output CSV files and SAR stats. The program exists with the 'sysinfo.txt' file found in the directory.

The following error message is found in the logs of the PostgreSQL instance:

user=postgres,db=Temps : 1,188 ms,time=2017-04-11 10:33:32 CEST FATAL:  database "Temps : 1,188 ms" does not exist

Regards

**Comment by darold** [comment]
Hi,

To trap the error message returned by pgcluu_collectd run it in interactive mode, I mean without the -D option. But if you use the latest development code from github the issue might already be solved.

Best regards,

**Comment by pgrepli** [comment]
We have tested the version 3.0dev, it fixed this issue.
As we use "pgCluu" in Production site, we would also like to know when this version will be released.
Thanks

**Comment by darold** [comment]
I guess during my next four consecutive spare time days, which mean during my next holidays and probably at end of this month.

**Comment by pgrepli** [comment]
Hello,
Do you have any new roadmap for the release 3.0?
Thanks

**Comment by darold** [comment]
If everything goes as expected it will be out this weekend. I'm currently working to finalise the release, I still have to document the CGI mode and to extract the javascript code to be compliant with Debian packaging.

**Comment by darold** [comment]
Sorry but next release that was expected last week-end is delayed before the end of the month. I can not find time to close the few pending issues and build a release. This will be a maintenance release because the CGI mode will take too much time to fully complete and we need a release now.

**Comment by darold** [comment]
Please have a look at release 2.6 just published here https://github.com/darold/pgcluu/releases

**Comment by pgrepli** [comment]
Thank you for this release. According to my tests, I have few remarks for this release.

I have the following warnings during the installation:

[root] # perl Makefile.PL
Checking if your kit is complete...
Warning: the following files are missing in your kit:
    cgi-bin/resources/bean.js
    cgi-bin/resources/bootstrap-datetimepicker.js
    cgi-bin/resources/bootstrap.min.css_
    cgi-bin/resources/bootstrap.min.js
    cgi-bin/resources/datetimepicker.css
    cgi-bin/resources/font-awesome.min.css
    cgi-bin/resources/jqplot.barRenderer.min.js
    cgi-bin/resources/jqplot.canvasAxisTickRenderer.min.js
    cgi-bin/resources/jqplot.canvasTextRenderer.min.js
    cgi-bin/resources/jqplot.categoryAxisRenderer.min.js
    cgi-bin/resources/jqplot.cursor.min.js
    cgi-bin/resources/jqplot.dateAxisRenderer.min.js
    cgi-bin/resources/jqplot.highlighter.min.js
    cgi-bin/resources/jqplot.pieRenderer.min.js
    cgi-bin/resources/jqplot.pointLabels.min.js
    cgi-bin/resources/jquery.jqplot.min.css
    cgi-bin/resources/jquery.jqplot.min.js
    cgi-bin/resources/jquery.min.js
    cgi-bin/resources/pgcluu.css
    cgi-bin/resources/pgcluu.js
    cgi-bin/resources/pgcluu_slide.js
    cgi-bin/resources/sorttable.js
    cgi-bin/resources/underscore.js
Please inform the author.
Writing Makefile for pgCluu

I have tested with PostgreSQL 9.5 and 9.6, in both cases, I have Perl warnings while generating reports:

[postgres] $ pgcluu -o /tmp/report_pgcluu96/ /tmp/stat_pgcluu96/
Use of uninitialized value in addition (+) at /usr/local/bin/pgcluu line 4144.
Use of uninitialized value in addition (+) at /usr/local/bin/pgcluu line 4144.
Use of uninitialized value $bgwriter_stat{"checkpoints_timed"} in substitution (s///) at /usr/local/bin/pgcluu line 4152.
Use of uninitialized value $bgwriter_stat{"checkpoints_req"} in substitution (s///) at /usr/local/bin/pgcluu line 4153.
Use of uninitialized value $bgwriter_stat{"buffers_checkpoint"} in substitution (s///) at /usr/local/bin/pgcluu line 4162.
Use of uninitialized value $bgwriter_stat{"buffers_clean"} in substitution (s///) at /usr/local/bin/pgcluu line 4163.
Use of uninitialized value $bgwriter_stat{"buffers_backend"} in substitution (s///) at /usr/local/bin/pgcluu line 4164.
Use of uninitialized value $bgwriter_stat{"buffers_alloc"} in substitution (s///) at /usr/local/bin/pgcluu line 4165.
Use of uninitialized value $bgwriter_stat{"maxwritten_clean"} in substitution (s///) at /usr/local/bin/pgcluu line 4168.
Use of uninitialized value $bgwriter_stat{"buffers_backend_fsync"} in substitution (s///) at /usr/local/bin/pgcluu line 4169.

The status of the command line is '0'.
The Perl version used is v5.16.3.

Regards

**Comment by darold** [comment]
Commit 0b260a3 fixes the MANIFEST, about the second issue I will investigate more because this case might not append. I guess you have run pgcluu too early, if you execute it again now do you have the same warning about uninitialized value?

**Comment by pgrepli** [comment]
I have tested the lastest "master" ZIP file, I do not have warnings in compilation, but still have the same warnings with generating reports.

I follow the same steps described in README:

mkdir /tmp/stat_db1/
pgcluu_collectd -D -i 60 /tmp/stat_db1/
pgcluu_collectd -k
mkdir /tmp/report_db1/
pgcluu -o /tmp/report_db1/ /tmp/stat_db1/
Use of uninitialized value in addition (+) at /usr/local/bin/pgcluu line 4144.
Use of uninitialized value in addition (+) at /usr/local/bin/pgcluu line 4144.
Use of uninitialized value $bgwriter_stat{"checkpoints_timed"} in substitution (s///) at /usr/local/bin/pgcluu line 4152.
Use of uninitialized value $bgwriter_stat{"checkpoints_req"} in substitution (s///) at /usr/local/bin/pgcluu line 4153.
Use of uninitialized value $bgwriter_stat{"buffers_checkpoint"} in substitution (s///) at /usr/local/bin/pgcluu line 4162.
Use of uninitialized value $bgwriter_stat{"buffers_clean"} in substitution (s///) at /usr/local/bin/pgcluu line 4163.
Use of uninitialized value $bgwriter_stat{"buffers_backend"} in substitution (s///) at /usr/local/bin/pgcluu line 4164.
Use of uninitialized value $bgwriter_stat{"buffers_alloc"} in substitution (s///) at /usr/local/bin/pgcluu line 4165.
Use of uninitialized value $bgwriter_stat{"maxwritten_clean"} in substitution (s///) at /usr/local/bin/pgcluu line 4168.
Use of uninitialized value $bgwriter_stat{"buffers_backend_fsync"} in substitution (s///) at /usr/local/bin/pgcluu line 4169.

What do you mean by "run pgcluu too early" ?

**Comment by darold** [comment]
I was thinking this comes just before file pg_stat_bgwriter.csv was generate. Can you post post here some lines of this file?

**Comment by pgrepli** [comment]
As I did a short test, I have one line in the file:
$ cat pg_stat_bgwriter.csv
2017-07-13 11:39:32+02;286;0;4017;34;40;0;0;0;0;1309;2017-07-12 11:48:11+02

I think I undertood the issue. When I run the test longer, I found too lines in the file, then I do not the warnings while generating reports.
$ cat pg_stat_bgwriter.csv
2017-07-13 17:36:23+02;357;2;4121;51;64;0;0;0;0;1374;2017-07-12 11:48:11+02
2017-07-13 17:37:24+02;357;2;4121;51;64;0;0;0;0;1649;2017-07-12 11:48:11+02

But this behavious is not happened in the previous release.

**Comment by darold** [comment]
This is because the first line is taken as an origin now to autodetect the inteval beween and its values are not stored anymore to compute the report. pgcluu is ran too early, but I will try to avoid the warning. I keep the issue open until it is fixed.
