### ISSUE TITLE
pgcluu -o report generation

### ISSUE THREAD

**Issue by cr2015** [darold/pgcluu#89]
When generating reports, if the directory has existing HTML reports, displays output directory is not empty.    Is there command line switches to overwrite the older HTML reports?

**Comment by darold** [comment]
No, in this mode you have to remove the directory content by hand before running pgcluu again but if you want to preserve all your report you can use the incremental mode.

Run pgcluu_collectd with the `--rotate-daily` this will enable the incremental mode and pgcluu will create a tree of subdirectory per day. Then run pgcluu as usual.

Is that what you was looking for?

**Comment by cr2015** [comment]
I would like to run pgcluu_collectd to collect statistics every 15 minutes or so.  Once new statistics are collected, I would like to generate the new reports to publish the HTML.

pgcluu_collectd will overwrite the older statistics files (csv), but when using pgcluu -o {output_report} {input_dir} when the {output_report} directory contains HTML files.

**Comment by cr2015** [comment]
error message stating output directory is not empty.

**Comment by darold** [comment]
Yes this is a limitation of the current implementation. But what you can try is running pgcluu_collectd in daemon mode and keep it running all the day. Running it each 15 minutes seems to me to have no interest. Try the following, run pgcluu_collectd in daemon and incremental mode:
```
/usr/local/bin/pgcluu_collectd -D --rotate-daily /var/lib/pgcluu_data/
```

it will run all the time until you reboot the machine or there is not enough space in the /var/lib/pgcluu_data/ output directory or you kill it using: `/usr/local/bin/pgcluu_collectd -k`

Then run pgcluu each 15 minutes by cron as follow:
```
*/15 * * * * /bin/rm -rf /var/www/pgcluu/*; /usr/local/bin/pgcluu -o /var/www/pgcluu/ /var/lib/pgcluu_data/`date +%Y/%m/%d`
```

This will rebuild the report of the current day each 15 minutes. This is not really optimum but this is the only way you can use it with the static HTML output. If you have an httpd server on the host where pgcluu is used you can use the CGI mode which allow you to have a full dynamic web interface to look at statistics over the time. This is a work in progress but it works so if you want to try I can help you to setup  your installation.

Regards,

**Comment by darold** [comment]
In next major release it will be possible to received alert when some warning and critical threshold will be reached. This is on my todo list.

**Comment by cr2015** [comment]
Thanks again, but for now if you implement as you directed above, this will provide information/details on the progress cluster every 'xx' minutes

**Comment by cr2015** [comment]
correction, if 'we' implement as your directed above...

**Comment by darold** [comment]
Yes you will have the information/details on the progress cluster every 'xx' minutes with graphs showing the  full day statistics history. This is mandatory to understand how issues appears. If you just run it each 'xx' minutes without incremental mode you will have only the statistics at the time you've ran it.
