### ISSUE TITLE
2.6 Incomplete "kit"

### ISSUE THREAD

**Issue by ras5429** [darold/pgcluu#90]
$ perl Makefile.PL --prefix=/apps/software
Checking if your kit is complete...
Warning: the following files are missing in your kit:
        cgi-bin/resources/bean.js
        cgi-bin/resources/bootstrap-datetimepicker.js
        cgi-bin/resources/bootstrap.min.css
        cgi-bin/resources/bootstrap.min.js
        cgi-bin/resources/datetimepicker.css
        cgi-bin/resources/font-awesome.min.css
        cgi-bin/resources/jqplot.barRenderer.min.js
        cgi-bin/resources/jqplot.canvasAxisTickRenderer.min.js
        cgi-bin/resources/jqplot.canvasTextRenderer.min.js
        cgi-bin/resources/jqplot.categoryAxisRenderer.min.js
        cgi-bin/resources/jqplot.cursor.min.js
        cgi-bin/resources/jqplot.dateAxisRenderer.min.js
        cgi-bin/resources/jqplot.highlighter.min.js
        cgi-bin/resources/jqplot.pieRenderer.min.js
        cgi-bin/resources/jqplot.pointLabels.min.js
        cgi-bin/resources/jquery.jqplot.min.css
        cgi-bin/resources/jquery.jqplot.min.js
        cgi-bin/resources/jquery.min.js
        cgi-bin/resources/pgcluu.css
        cgi-bin/resources/pgcluu.js
        cgi-bin/resources/pgcluu_slide.js
        cgi-bin/resources/sorttable.js
        cgi-bin/resources/underscore.js
Please inform the author.
Writing Makefile for pgCluu

**Comment by darold** [comment]
Thanks for the report, it has been fixed in commit 0b260a3
