### ISSUE TITLE
pgcluu report outputs.

### ISSUE THREAD

**Issue by TheSebamed** [darold/pgcluu#94]
Hello!

I am here trying to get my crontab working but it seem to be not do what i want it to do.

Currently, im running my pgcluu with this command.
 pgcluu_collectd --daemonize --rotate-hourly  /var/www/html/pgcluu/stats

I have tested a command that will make a folder and move the stats to report folder (with the specific date)
mkdir -p /var/www/html/pgcluu/reports/$(date +"%Y/%m/%d/%H/") && pgcluu -o /var/www/html/pgcluu/reports/$(date +"%Y/%m/%d/%H/") /var/www/html/pgcluu/stats/$(date +"%Y/%m/%d/%H/") 
 ( not needed right now) >/dev/null 2>&1
So i have also made a cron use this command with the following.

3 * * * * postgres mkdir -p /var/www/html/pgcluu/reports/$(date +"%Y/%m/%d/%H/") && pgcluu -o /var/www/html/pgcluu/reports/$(date +"%Y/%m/%d/%H/") /var/www/html/pgcluu/stats/$(date +"%Y/%m/%d/%H/") >/dev/null 2>&1

And for some reasons it seems cron is not working as the way i made it, it does not want to do it. Any idea if im doing something wrong? as the command itself works perfectly in a postgres account.

EDIT: Also tried this with contab.

28 * * * * postgres /bin/rm -rf /var/www/html/pgcluu/reports/*; pgcluu -o /var/www/html/pgcluu/reports/ /var/www/html/pgcluu/stats/`date +%Y/%m/%d/%H` >/dev/null 2>&1

Something seems to be wrong with Cron?

**Comment by darold** [comment]
As seen privatly for this kind of usage I recommand the use of the CGI mode of pgCluu.
