### ISSUE TITLE
pgcluu_collectd not generating new statistic files

### ISSUE THREAD

**Issue by TheSebamed** [darold/pgcluu#95]
Hello!

I have already spoken with Darold bunch of times over mail, but i decided to bring some of the topic over here as some others might experience the same issue as i am.

I downloaded the latest update, which fixed a bug in CGI, as Darold mentioned.

I was using the old 2.6v pgCluu for 2 weeks. It was working fine. It was generating reports and was collecting data perfectly.

About a week ago, something happened. I have no idea what, but pgcluu_collect is not rewriting the data it should.
I start my collect with

`pgcluu_collectd -D -i 60 --rotate-daily /var/www/pgcluu/stats`

At first, it was writing the data perfectly. All the folder/file permissions were Read/Write for Owner/Group.
Then suddenly, it went to Read/Write for Owner and Read for Group.

Then i used ACL's to keep all the new files generated as `Read/Write for Owner/Group`

Now, when i now start the collectd process, it generates the first files and then afew minutes later the second files `csv`

I have link for all the files that are generated [https://pastebin.com/raw/gnMwda8i](url)

I reinstalled pgCluu on my test machine and everything works fine there. But on my Real postgres server, it is not.

Edit: I thought of trying to see if `Sar works` 
So, i  tried `sar -p -A -D 10 60 > /var/www/pgcluu/stats/sar.txt` and it is generating with `Sar`

**Comment by darold** [comment]
The CGI part of pgcluu require some additional knowledge about how Apache server works, I try to keep thing simple to be able to execute pgcluu but I can't do much more about the Apache configuration.  Unfortunately I still not have time to document the CGI installation and configuration task but it will be available in next major release 3.0. I will work on this this summer.
