### ISSUE TITLE
pgcluu not graphing correctly data retrieved from pgbouncer 1.8+

### ISSUE THREAD

**Issue by fabioporta** [darold/pgcluu#96]
Since version 1.8 of pgbouncer, the command 'show stats' changed output. Some fields have been added, others renamed. Therefore graphs coming out of pgcluu are not showing out as expected (pgbouncer queries duration and queries per second)

pgbouncer, 'SHOW STATS'
```
old output:
----------------------------------
database         | pgbouncer
total_requests   | 1
total_received   | 0
total_sent       | 0
total_query_time | 0
avg_req          | 0
avg_recv         | 0
avg_sent         | 0
avg_query        | 0
----------------------------------
```
new output:
```
----------------------------------
database          | pgbouncer
total_xact_count  | 20389
total_query_count | 20389
total_received    | 0
total_sent        | 0
total_xact_time   | 0
total_query_time  | 0
total_wait_time   | 0
avg_xact_count    | 0
avg_query_count   | 0
avg_recv          | 0
avg_sent          | 0
avg_xact_time     | 0
avg_query_time    | 0
avg_wait_time     | 0
----------------------------------
```
While i'm using crafted scripts to retrieve pgbouncer data on each backend, I noticed that pgcluu did not update its code since the release. (for the simple reason that the latest release of pgcluu is older than pgbouncer 1.8). (Therefore: cannot validate my changes, since i do not have a testbed)

I believe that this part of pgcluu code should be changed accordingly, in order to satisfy the new/changed fields:
```
		$all_pgbouncer_req_stats{$data[0]}{$data[1]}{total_requests} += $data[2];
		$all_pgbouncer_req_stats{$data[0]}{$data[1]}{total_received} += $data[3];
		$all_pgbouncer_req_stats{$data[0]}{$data[1]}{total_sent} += $data[4];
		$all_pgbouncer_req_stats{$data[0]}{$data[1]}{total_query_time} += $data[5];
		$all_pgbouncer_req_stats{$data[0]}{$data[1]}{avg_req} += $data[6];
		$all_pgbouncer_req_stats{$data[0]}{$data[1]}{avg_recv} += $data[7];
		$all_pgbouncer_req_stats{$data[0]}{$data[1]}{avg_sent} += $data[8];
		$all_pgbouncer_req_stats{$data[0]}{$data[1]}{avg_query} += $data[9];
```

as a side note, this is the mapping old-new fields:
```
total_requests        -> total_query_count 
total_received        - > total_received
total_sent              -> total_sent
total_query_time    -> total_query_time
avg_req                 -> avg_query_count
avg_recv               -> avg_recv
avg_sent               -> avg_sent
avg_query_time     -> avg_query_time
```

**Comment by darold** [comment]
Thanks for the report and especially for the mapping it saves me lot of time. Commit afdc0e7 adds the compatibility with pgbouncer 1.8. I have not tried with a live pgbouncer as I'm traveling so let me know if all is working for you.

I see also that there is two new interesting information about wait time, I will add a report to show the time waiting from the server.

**Comment by darold** [comment]
Commit 9def072 adds reports about wait statistic, it also fix report on total stats that was not relative to the previous value collected. I finally found time to install pgbouncer 1.8 and test it, all might works as expected.

**Comment by darold** [comment]
Good news, thanks for the report.
